version: 2019.{build}
branches:
  only:
  - master
  - appveyor
image:
- Ubuntu1804
- Ubuntu1604
clone_folder: c:\lede
build:
   git clone https://github.com/coolsnowwolf/lede 命令下载好源代码，然后 cd lede 进入目录
  sudo apt-get update&&apt-get upgrade -y
  sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint
   ./scripts/feeds update -a
   ./scripts/feeds install -a
   make menuconfig
   make -j1 V=s
  verbosity: minimal