version: 2019.{build}
branches:
  only:
  - appveyor
  - master
image:
- Ubuntu1804
platform:
- Any CPU
- x86
- x64
- ARM
environment:
  matrix:
  - {}
install:
- ps: >-
    sudo apt-get update

    sudo apt-get upgrade -y

    sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint

    git clone https://github.com/dingpengyu/lede.git

    cd lede
before_build:
- pwsh: >-
    sudo apt-get update

    sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint

    git clone https://github.com/dingpengyu/lede.git

    ./scripts/feeds update -a

    ./scripts/feeds install -a

    make menuconfig
build:
  verbosity: normal