name: Auto Close PR
on:
  pull_request_target:
    types: [opened]

jobs:
  auto_close_pr:
    runs-on: ubuntu-latest
    if: github.repository == 'coolsnowwolf/lede'
    steps:
    - uses: imba-tjd/auto-close-pr-action@0.3.1
      with:
        pattern: '* [x] 我知道'
