
#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: 云编译X86 
on:
  push:
    branches: 
      - master     
      #     ↑↑↑ 改成你的分支名, 一般是master
       
  schedule: 
    - cron: 30 0 * * * 
    #     ↑↑↑ 设置开始编译时间。格式为UTC，即北京时间减去8小时……，如：0 0 * * 1，为北京时间每周一的早上8点开始编译……
       
  # release:
  #   types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检测-Checkout
        uses: actions/checkout@master
        with:
          ref: master
        #      ↑↑↑ 改成你的分支名, 一般是master

      - name: 初始化环境-Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          echo "Deleting files, please wait ..."
          sudo rm -rf \
            /usr/share/dotnet \
            /etc/mysql \
            /etc/php
          sudo -E apt-get -y purg
