#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: Merge-upstream

on:
  push:
    branches: 
      - master
  schedule:
    - cron: 30 19 * * *

jobs:
  merge:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: master
        fetch-depth: 0
        lfs: true

    - name: Set git identity
      run : |
        git config --global user.email "13757260730@sina.cn"
        git config --global user.name "fyfh"
    
    - name: Load upstream commits
      run : |
        git remote add upstream https://github.com/coolsnowwolf/lede.git
        git remote -v
        git fetch upstream
        git add -A 
        git commit -m "your note"

    - name: Push Commits
      run : |
        git merge upstream/master
        git push origin master
