#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: OpenWrt-CI

on:
  push:
    branches: 
      - master
  # schedule:
  #   - cron: 0 20 * * *
  # release:
  #   types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

          # sudo mkdir -p -m 777 /mnt/openwrt/bin /mnt/openwrt/build_dir/host /mnt/openwrt/build_dir/hostpkg /mnt/openwrt/dl /mnt/openwrt/feeds /mnt/openwrt/staging_dir
          # ln -s /mnt/openwrt/bin ./bin
          # mkdir -p ./build_dir/host && ln -s /mnt/openwrt/build_dir/host ./build_dir/host
          # mkdir -p ./build_dir/host && ln -s /mnt/openwrt/build_dir/hostpkg ./build_dir/hostpkg
          # ln -s /mnt/openwrt/dl ./dl
          # ln -s /mnt/openwrt/feeds ./feeds
          # ln -s /mnt/openwrt/staging_dir ./staging_dir

          df -h

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate configuration file
        run: |
          rm -f ./.config*
          touch ./.config

          #
          # ========================固件定制部分========================
          # 

          # 
          # 如果不对本区块做出任何编辑, 则生成默认配置固件. 
          # 

          # 以下为定制化固件选项和说明:
          #

          #
          # 有些插件/选项是默认开启的, 如果想要关闭, 请参照以下示例进行编写:
          # 
          #          =========================================
          #         |  # 取消编译VMware镜像:                   |
          #         |  cat >> .config <<EOF                   |
          #         |  # CONFIG_VMDK_IMAGES is not set        |
          #         |  EOF                                    |
          #          =========================================
          #

          # 
          # 以下是一些提前准备好的一些插件选项.
          # 直接取消注释相应代码块即可应用. 不要取消注释代码块上的汉字说明.
          # 如果不需要代码块里的某一项配置, 只需要删除相应行.
          #
          # 如果需要其他插件, 请按照示例自行添加.
          # 注意, 只需添加依赖链顶端的包. 如果你需要插件 A, 同时 A 依赖 B, 即只需要添加 A.
          # 
          # 无论你想要对固件进行怎样的定制, 都需要且只需要修改 EOF 回环内的内容.
          # 

          # 编译x64固件:
          # cat >> .config <<EOF
          # CONFIG_TARGET_x86=y
          # CONFIG_TARGET_x86_64=y
          # CONFIG_TARGET_x86_64_Generic=y
          # EOF
          
           cat >> .config <<EOF
            CONFIG_TARGET_ramips=y
            CONFIG_TARGET_ramips_mt7621=y
            CONFIG_TARGET_ramips_mt7621_DEVICE_d-team_newifi-d2=y
            CONFIG_HAS_SUBTARGETS=y
            CONFIG_HAS_DEVICES=y
            CONFIG_TARGET_BOARD="ramips"
            CONFIG_TARGET_SUBTARGET="mt7621"
            CONFIG_TARGET_PROFILE="DEVICE_d-team_newifi-d2"
            CONFIG_TARGET_ARCH_PACKAGES="mipsel_24kc"
            CONFIG_DEFAULT_TARGET_OPTIMIZATION="-Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc"
            CONFIG_CPU_TYPE="24kc"
           EOF

          # 固件压缩:
          # cat >> .config <<EOF
          # CONFIG_TARGET_IMAGES_GZIP=y
          # EOF
          
          cat >> .config <<EOF
          CONFIG_TARGET_INITRAMFS_COMPRESSION_LZMA=y
          EOF
          # 编译UEFI固件:
          # cat >> .config <<EOF
          # CONFIG_EFI_IMAGES=y
          # EOF

          # IPv6支持:
          # cat >> .config <<EOF
          # CONFIG_PACKAGE_dnsmasq_full_dhcpv6=y
          # CONFIG_PACKAGE_ipv6helper=y
          # EOF

          # 多文件系统支持:
          # cat >> .config <<EOF
          # CONFIG_PACKAGE_kmod-fs-nfs=y
          # CONFIG_PACKAGE_kmod-fs-nfs-common=y
          # CONFIG_PACKAGE_kmod-fs-nfs-v3=y
          # CONFIG_PACKAGE_kmod-fs-nfs-v4=y
          # CONFIG_PACKAGE_kmod-fs-ntfs=y
          # CONFIG_PACKAGE_kmod-fs-squashfs=y
          # EOF
          
          #軟件
           cat >> .config <<EOF
            CONFIG_PACKAGE_dnsmasq-full=y
            CONFIG_PACKAGE_dnsmasq_full_dhcp=y
            CONFIG_PACKAGE_dnsmasq_full_ipset=y
            CONFIG_PACKAGE_dropbear=y
            CONFIG_DROPBEAR_CURVE25519=y
            CONFIG_PACKAGE_firewall=y
            CONFIG_PACKAGE_fstools=y
            CONFIG_FSTOOLS_UBIFS_EXTROOT=y
            CONFIG_PACKAGE_fwtool=y
            CONFIG_PACKAGE_jsonfilter=y
            CONFIG_PACKAGE_libc=y
            CONFIG_PACKAGE_libgcc=y
            CONFIG_PACKAGE_libpthread=y
            CONFIG_PACKAGE_librt=y
            CONFIG_PACKAGE_libstdcpp=y
            CONFIG_PACKAGE_logd=y
            CONFIG_PACKAGE_mtd=y
            CONFIG_PACKAGE_netifd=y
            CONFIG_PACKAGE_openwrt-keyring=y
            CONFIG_PACKAGE_opkg=y
            CONFIG_PACKAGE_procd=y
            CONFIG_PACKAGE_qos-scripts=m
            CONFIG_PACKAGE_rpcd=y
            CONFIG_PACKAGE_sqm-scripts=y
            CONFIG_PACKAGE_swconfig=y
            CONFIG_PACKAGE_ubox=y
            CONFIG_PACKAGE_ubus=y
            CONFIG_PACKAGE_ubusd=y
            CONFIG_PACKAGE_uci=y
            CONFIG_PACKAGE_usign=y
            CONFIG_PACKAGE_automount=y
            CONFIG_PACKAGE_autosamba=m
            CONFIG_PACKAGE_wireless-regdb=y
            CONFIG_PACKAGE_kmod-scsi-core=y
            CONFIG_PACKAGE_kmod-crypto-aead=y
            CONFIG_PACKAGE_kmod-crypto-arc4=y
            CONFIG_PACKAGE_kmod-crypto-authenc=y
            CONFIG_PACKAGE_kmod-crypto-crc32c=y
            CONFIG_PACKAGE_kmod-crypto-ecb=y
            CONFIG_PACKAGE_kmod-crypto-hash=y
            CONFIG_PACKAGE_kmod-crypto-manager=y
            CONFIG_PACKAGE_kmod-crypto-null=y
            CONFIG_PACKAGE_kmod-crypto-pcompress=y
            CONFIG_PACKAGE_kmod-crypto-sha1=y
            CONFIG_PACKAGE_kmod-cryptodev=y
            CONFIG_PACKAGE_kmod-fs-exfat=y
            CONFIG_PACKAGE_kmod-fs-ext4=y
            CONFIG_PACKAGE_kmod-fs-vfat=y
            CONFIG_PACKAGE_kmod-fuse=y
            CONFIG_PACKAGE_kmod-leds-gpio=y
            CONFIG_PACKAGE_kmod-lib-crc-ccitt=y
            CONFIG_PACKAGE_kmod-lib-crc16=y
            CONFIG_PACKAGE_kmod-lib-textsearch=y
            CONFIG_PACKAGE_kmod-nls-base=y
            CONFIG_PACKAGE_kmod-nls-cp437=y
            CONFIG_PACKAGE_kmod-nls-iso8859-1=y
            CONFIG_PACKAGE_kmod-nls-utf8=y
            CONFIG_PACKAGE_kmod-ipt-conntrack=y
            CONFIG_PACKAGE_kmod-ipt-conntrack-extra=y
            CONFIG_PACKAGE_kmod-ipt-core=y
            CONFIG_PACKAGE_kmod-ipt-fullconenat=y
            CONFIG_PACKAGE_kmod-ipt-ipopt=y
            CONFIG_PACKAGE_kmod-ipt-ipset=y
            CONFIG_PACKAGE_kmod-ipt-nat=y
            CONFIG_PACKAGE_kmod-ipt-offload=y
            CONFIG_PACKAGE_kmod-ipt-raw=y
            CONFIG_PACKAGE_kmod-nf-conntrack=y
            CONFIG_PACKAGE_kmod-nf-conntrack-netlink=y
            CONFIG_PACKAGE_kmod-nf-conntrack6=y
            CONFIG_PACKAGE_kmod-nf-flow=y
            CONFIG_PACKAGE_kmod-nf-ipt=y
            CONFIG_PACKAGE_kmod-nf-nat=y
            CONFIG_PACKAGE_kmod-nf-nathelper=y
            CONFIG_PACKAGE_kmod-nf-nathelper-extra=y
            CONFIG_PACKAGE_kmod-nf-reject=y
            CONFIG_PACKAGE_kmod-nfnetlink=y
            CONFIG_PACKAGE_kmod-ifb=y
            CONFIG_PACKAGE_kmod-ppp=y
            CONFIG_PACKAGE_kmod-mppe=y
            CONFIG_PACKAGE_kmod-pppoe=y
            CONFIG_PACKAGE_kmod-pppox=y
            CONFIG_PACKAGE_kmod-sched-cake=y
            CONFIG_PACKAGE_kmod-sched-connmark=m
            CONFIG_PACKAGE_kmod-sched-core=y
            CONFIG_PACKAGE_kmod-slhc=y
            CONFIG_PACKAGE_kmod-tcp-bbr=y
            CONFIG_PACKAGE_kmod-tun=y
            CONFIG_PACKAGE_kmod-gpio-button-hotplug=y
            CONFIG_PACKAGE_kmod-usb-core=y
            CONFIG_PACKAGE_kmod-usb-ledtrig-usbport=y
            CONFIG_PACKAGE_kmod-usb-storage=y
            CONFIG_PACKAGE_kmod-usb-storage-extras=y
            CONFIG_PACKAGE_kmod-usb3=y
            CONFIG_PACKAGE_kmod-cfg80211=y
            CONFIG_PACKAGE_kmod-mac80211=y
            CONFIG_PACKAGE_MAC80211_DEBUGFS=y
            CONFIG_PACKAGE_MAC80211_MESH=y
            CONFIG_PACKAGE_kmod-mt76-core=y
            CONFIG_PACKAGE_kmod-mt7603=y
            CONFIG_PACKAGE_kmod-mt76x02-common=y
            CONFIG_PACKAGE_kmod-mt76x2=y
            CONFIG_PACKAGE_kmod-mt76x2-common=y
            CONFIG_PACKAGE_libiwinfo-lua=y
            CONFIG_PACKAGE_lua=y
            CONFIG_PACKAGE_libip4tc=y
            CONFIG_PACKAGE_libip6tc=y
            CONFIG_PACKAGE_libxtables=y
            CONFIG_PACKAGE_libopenssl=y
            CONFIG_PACKAGE_libopenssl-conf=y
            CONFIG_PACKAGE_libopenssl-devcrypto=y
            CONFIG_PACKAGE_libblobmsg-json=y
            CONFIG_PACKAGE_libelf=y
            CONFIG_PACKAGE_libiwinfo=y
            CONFIG_PACKAGE_libjson-c=y
            CONFIG_PACKAGE_liblua=y
            CONFIG_PACKAGE_liblzo=y
            CONFIG_PACKAGE_libmnl=y
            CONFIG_PACKAGE_libnl-tiny=y
            CONFIG_PACKAGE_libpcre=y
            CONFIG_PACKAGE_libubox=y
            CONFIG_PACKAGE_libubus=y
            CONFIG_PACKAGE_libubus-lua=y
            CONFIG_PACKAGE_libuci=y
            CONFIG_PACKAGE_libuci-lua=y
            CONFIG_PACKAGE_libuclient=y
            CONFIG_PACKAGE_rpcd-mod-rrdns=y
            CONFIG_PACKAGE_zlib=y
            CONFIG_PACKAGE_luci=y
            CONFIG_PACKAGE_luci-base=y
            CONFIG_PACKAGE_luci-mod-admin-full=y
            CONFIG_PACKAGE_luci-app-accesscontrol=y
            CONFIG_PACKAGE_luci-app-adbyby-plus=y
            CONFIG_PACKAGE_luci-app-aria2=y
            CONFIG_PACKAGE_luci-app-arpbind=y
            CONFIG_PACKAGE_luci-app-autoreboot=y
            CONFIG_PACKAGE_luci-app-firewall=y
            CONFIG_PACKAGE_luci-app-hd-idle=y
            CONFIG_PACKAGE_luci-app-nlbwmon=y
            CONFIG_PACKAGE_luci-app-openvpn-server=y
            CONFIG_PACKAGE_luci-app-qos=m
            CONFIG_PACKAGE_luci-app-ramfree=y
            CONFIG_PACKAGE_luci-app-samba=m
            CONFIG_PACKAGE_luci-app-sqm=y
            CONFIG_PACKAGE_luci-app-vsftpd=y
            CONFIG_PACKAGE_luci-theme-bootstrap=y
            CONFIG_PACKAGE_luci-proto-ppp=y
            CONFIG_PACKAGE_luci-lib-ip=y
            CONFIG_PACKAGE_luci-lib-jsonc=y
            CONFIG_PACKAGE_luci-lib-nixio=y
            CONFIG_PACKAGE_default-settings=y
            CONFIG_PACKAGE_luci-i18n-accesscontrol-zh-cn=y
            CONFIG_PACKAGE_luci-i18n-adbyby-plus-zh-cn=y
            CONFIG_PACKAGE_luci-i18n-aria2-zh-cn=y
            CONFIG_PACKAGE_luci-i18n-arpbind-zh-cn=y
            CONFIG_PACKAGE_luci-i18n-autoreboot-zh-cn=y
            CONFIG_PACKAGE_luci-i18n-base-zh-cn=y
            CONFIG_PACKAGE_luci-i18n-firewall-zh-cn=y
            CONFIG_PACKAGE_luci-i18n-hd-idle-zh-cn=y
            CONFIG_PACKAGE_luci-i18n-nlbwmon-zh-cn=y
            CONFIG_PACKAGE_luci-i18n-openvpn-server-zh-cn=y
            CONFIG_PACKAGE_luci-i18n-qos-zh-cn=m
            CONFIG_PACKAGE_luci-i18n-ramfree-zh-cn=y
            CONFIG_PACKAGE_luci-i18n-samba-zh-cn=m
            CONFIG_PACKAGE_luci-i18n-vsftpd-zh-cn=y
            CONFIG_PACKAGE_wget=y
            CONFIG_PACKAGE_iptables=y
            CONFIG_PACKAGE_iptables-mod-conntrack-extra=y
            CONFIG_PACKAGE_iptables-mod-fullconenat=y
            CONFIG_PACKAGE_iptables-mod-ipopt=y
            CONFIG_PACKAGE_ip-full=y
            CONFIG_PACKAGE_tc=y
            CONFIG_PACKAGE_openvpn-easy-rsa=y
            CONFIG_PACKAGE_openvpn-openssl=y
            CONFIG_PACKAGE_uhttpd=y
            CONFIG_PACKAGE_uhttpd-mod-ubus=y
            CONFIG_PACKAGE_adbyby=y
            CONFIG_PACKAGE_hostapd-common=y
            CONFIG_PACKAGE_ipset=y
            CONFIG_PACKAGE_iw=y
            CONFIG_PACKAGE_libipset=y
            CONFIG_PACKAGE_nlbwmon=y
            CONFIG_PACKAGE_ppp=y
            CONFIG_PACKAGE_ppp-mod-pppoe=y
            CONFIG_PACKAGE_samba36-server=m
            CONFIG_PACKAGE_SAMBA_MAX_DEBUG_LEVEL=-1
            CONFIG_PACKAGE_uclient-fetch=y
            CONFIG_PACKAGE_wpad-openssl=y
            CONFIG_PACKAGE_hd-idle=y
            CONFIG_PACKAGE_ntfs-3g=y
            CONFIG_PACKAGE_coremark=y
            CONFIG_PACKAGE_coreutils=y
            CONFIG_PACKAGE_coreutils-nohup=y
            CONFIG_PACKAGE_jshn=y
            CONFIG_PACKAGE_libjson-script=y
            CONFIG_PACKAGE_openssl-util=y
            CONFIG_PACKAGE_shellsync=y
            CONFIG_PACKAGE_ubi-utils=y
           EOF
          

          # USB3.0支持:
          # cat >> .config <<EOF
          # CONFIG_PACKAGE_kmod-usb-ohci=y
          # CONFIG_PACKAGE_kmod-usb-ohci-pci=y
          # CONFIG_PACKAGE_kmod-usb2=y
          # CONFIG_PACKAGE_kmod-usb2-pci=y
          # CONFIG_PACKAGE_kmod-usb3=y
          # EOF

          # 常用LuCI插件选择:
          # cat >> .config <<EOF
          # CONFIG_PACKAGE_luci-app-adbyby-plus=y
          # CONFIG_PACKAGE_luci-app-aria2=y
          # CONFIG_PACKAGE_luci-app-baidupcs-web=y
          # CONFIG_PACKAGE_luci-app-docker=y
          # CONFIG_PACKAGE_luci-app-frpc=y
          # CONFIG_PACKAGE_luci-app-kodexplorer=y
          # CONFIG_PACKAGE_luci-app-minidlna=y
          # CONFIG_PACKAGE_luci-app-openvpn=y
          # CONFIG_PACKAGE_luci-app-openvpn-server=y
          # CONFIG_PACKAGE_luci-app-qbittorrent=y
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Kcptun=y
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Shadowsocks=y
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Server=y
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Socks=y
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray=y
          # CONFIG_PACKAGE_luci-app-ttyd=y
          # CONFIG_PACKAGE_luci-app-v2ray-server=y
          # CONFIG_PACKAGE_luci-app-verysync=y
          # CONFIG_PACKAGE_luci-app-webadmin=y
          # CONFIG_PACKAGE_luci-app-wireguard=y
          # CONFIG_PACKAGE_luci-app-wrtbwmon=y
          # EOF

          # LuCI主题:
          # cat >> .config <<EOF
          # CONFIG_PACKAGE_luci-theme-argon=y
          # CONFIG_PACKAGE_luci-theme-netgear=y
          # EOF

          # 常用软件包:
          # cat >> .config <<EOF
          # CONFIG_PACKAGE_curl=y
          # CONFIG_PACKAGE_htop=y
          # CONFIG_PACKAGE_nano=y
          # CONFIG_PACKAGE_screen=y
          # CONFIG_PACKAGE_tree=y
          # CONFIG_PACKAGE_vim-fuller=y
          # CONFIG_PACKAGE_wget=y
          # EOF

          # 取消编译VMware镜像以及镜像填充 (不要删除被缩进的注释符号):
          # cat >> .config <<EOF
          # # CONFIG_TARGET_IMAGES_PAD is not set
          # # CONFIG_VMDK_IMAGES is not set
          # EOF

          # 
          # ========================固件定制部分结束========================
          # 

          sed -i 's/^[ \t]*//g' ./.config
          make defconfig

      - name: Make download
        run: |
          make download -j8
          find ./dl/ -size -1024c -exec rm -f {} \;
          df -h

      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin

      - name: Prepare artifact
        run: find ./bin/targets/ -type d -name "packages" | xargs rm -rf {}

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt firmware
          path: ./bin/targets/
