#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: arch17自动编译

on:
  # push:
  #  branches: 
  #    - master
  # schedule:
  #   - cron: 0 20 * * *
  # release:
  #   types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          echo "Deleting files, please wait ..."
          sudo rm -rf \
            /usr/share/dotnet \
            /etc/mysql \
            /etc/php
          sudo -E apt-get -y purge \
            azure-cli \
            ghc* \
            zulu* \
            hhvm \
            llvm* \
            firefox \
            google* \
            dotnet* \
            powershell \
            openjdk* \
            mysql* \
            php*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Costom configure file
        run: |
          rm -f ./.config*
          touch ./.config

          #
          # ========================固件定制部分========================
          # 

          # 
          # 如果不对本区块做出任何编辑, 则生成默认配置固件. 
          # 

          # 以下为定制化固件选项和说明:
          #

          #
          # 有些插件/选项是默认开启的, 如果想要关闭, 请参照以下示例进行编写:
          # 
          #          =========================================
          #         |  # 取消编译VMware镜像:                   |
          #         |  cat >> .config <<EOF                   |
          #         |  # CONFIG_VMDK_IMAGES is not set        |
          #         |  EOF                                    |
          #          =========================================
          #

          # 
          # 以下是一些提前准备好的一些插件选项.
          # 直接取消注释相应代码块即可应用. 不要取消注释代码块上的汉字说明.
          # 如果不需要代码块里的某一项配置, 只需要删除相应行.
          #
          # 如果需要其他插件, 请按照示例自行添加.
          # 注意, 只需添加依赖链顶端的包. 如果你需要插件 A, 同时 A 依赖 B, 即只需要添加 A.
          # 
          # 无论你想要对固件进行怎样的定制, 都需要且只需要修改 EOF 回环内的内容.
          # 

          # 编译arch17固件:
          cat >> .config <<EOF
          CONFIG_TARGET_ipq40xx=y
          CONFIG_TARGET_ipq40xx_DEVICE_asus_rt-acrh17=y
          CONFIG_HAS_DEVICES=y
          CONFIG_TARGET_BOARD="ipq40xx"
          CONFIG_TARGET_SUBTARGET="generic"
          CONFIG_TARGET_PROFILE="DEVICE_asus_rt-acrh17"
          CONFIG_TARGET_ARCH_PACKAGES="arm_cortex-a7_neon-vfpv4"
          CONFIG_DEFAULT_TARGET_OPTIMIZATION="-Os -pipe"
          CONFIG_CPU_TYPE="cortex-a7+neon-vfpv4"
          CONFIG_LINUX_4_14=y
          CONFIG_DEFAULT_ath10k-firmware-qca4019=y
          CONFIG_DEFAULT_ath10k-firmware-qca9984=y
          CONFIG_DEFAULT_automount=y
          CONFIG_DEFAULT_autosamba=y
          CONFIG_DEFAULT_base-files=y
          CONFIG_DEFAULT_block-mount=y
          CONFIG_DEFAULT_busybox=y
          CONFIG_DEFAULT_ca-certificates=y
          CONFIG_DEFAULT_coremark=y
          CONFIG_DEFAULT_ddns-scripts_aliyun=y
          CONFIG_DEFAULT_default-settings=y
          CONFIG_DEFAULT_dnsmasq-full=y
          CONFIG_DEFAULT_dropbear=y
          CONFIG_DEFAULT_e2fsprogs=y
          CONFIG_DEFAULT_fdisk=y
          CONFIG_DEFAULT_firewall=y
          CONFIG_DEFAULT_fstools=y
          CONFIG_DEFAULT_htop=y
          CONFIG_DEFAULT_ipq-wifi-rt-acrh17=y
          CONFIG_DEFAULT_iptables=y
          CONFIG_DEFAULT_kmod-ath10k=y
          CONFIG_DEFAULT_kmod-gpio-button-hotplug=y
          CONFIG_DEFAULT_kmod-ipt-offload=y
          CONFIG_DEFAULT_kmod-ipt-raw=y
          CONFIG_DEFAULT_kmod-leds-gpio=y
          CONFIG_DEFAULT_kmod-nf-nathelper=y
          CONFIG_DEFAULT_kmod-nf-nathelper-extra=y
          CONFIG_DEFAULT_kmod-tcp-bbr=y
          CONFIG_DEFAULT_kmod-usb-dwc3=y
          CONFIG_DEFAULT_kmod-usb-dwc3-of-simple=y
          CONFIG_DEFAULT_kmod-usb3=y
          CONFIG_DEFAULT_libc=y
          CONFIG_DEFAULT_libgcc=y
          CONFIG_DEFAULT_logd=y
          CONFIG_DEFAULT_luci=y
          CONFIG_DEFAULT_luci-app-accesscontrol=y
          CONFIG_DEFAULT_luci-app-adbyby-plus=y
          CONFIG_DEFAULT_luci-app-arpbind=y
          CONFIG_DEFAULT_luci-app-autoreboot=y
          CONFIG_DEFAULT_luci-app-ddns=y
          CONFIG_DEFAULT_luci-app-filetransfer=y
          CONFIG_DEFAULT_luci-app-flowoffload=y
          CONFIG_DEFAULT_luci-app-ipsec-vpnd=y
          CONFIG_DEFAULT_luci-app-nlbwmon=y
          CONFIG_DEFAULT_luci-app-pptp-server=y
          CONFIG_DEFAULT_luci-app-qbittorrent=y
          CONFIG_DEFAULT_luci-app-ramfree=y
          CONFIG_DEFAULT_luci-app-sfe=y
          CONFIG_DEFAULT_luci-app-sqm=y
          CONFIG_DEFAULT_luci-app-ssr-plus=y
          CONFIG_DEFAULT_luci-app-unblockmusic=y
          CONFIG_DEFAULT_luci-app-upnp=y
          CONFIG_DEFAULT_luci-app-vlmcsd=y
          CONFIG_DEFAULT_luci-app-vsftpd=y
          CONFIG_DEFAULT_luci-app-wol=y
          CONFIG_DEFAULT_luci-app-xlnetacc=y
          CONFIG_DEFAULT_luci-app-zerotier=y
          CONFIG_DEFAULT_mtd=y
          CONFIG_DEFAULT_netifd=y
          CONFIG_DEFAULT_opkg=y
          CONFIG_DEFAULT_ppp=y
          CONFIG_DEFAULT_ppp-mod-pppoe=y
          CONFIG_DEFAULT_shadowsocks-libev-ss-redir=y
          CONFIG_DEFAULT_shadowsocksr-libev-server=y
          CONFIG_DEFAULT_swconfig=y
          CONFIG_DEFAULT_uci=y
          CONFIG_DEFAULT_uclient-fetch=y
          CONFIG_DEFAULT_v2ray=y
          CONFIG_DEFAULT_wget=y
          CONFIG_DEFAULT_wpad-openssl=y
          CONFIG_HAS_FPU=y
          CONFIG_AUDIO_SUPPORT=y
          CONFIG_GPIO_SUPPORT=y
          CONFIG_PCI_SUPPORT=y
          CONFIG_PCIE_SUPPORT=y
          CONFIG_USB_SUPPORT=y
          CONFIG_RTC_SUPPORT=y
          CONFIG_USES_DEVICETREE=y
          CONFIG_USES_INITRAMFS=y
          CONFIG_USES_SQUASHFS=y
          CONFIG_NAND_SUPPORT=y
          CONFIG_arm=y
          CONFIG_arm_v7=y
          CONFIG_ARCH="arm"
          EOF

          # 固件压缩:
          cat >> .config <<EOF
          CONFIG_TARGET_IMAGES_GZIP=y
          EOF

          # 编译UEFI固件:
          cat >> .config <<EOF
          CONFIG_EFI_IMAGES=y
          EOF

          # IPv6支持:
          cat >> .config <<EOF
          CONFIG_PACKAGE_dnsmasq_full_dhcpv6=y
          CONFIG_PACKAGE_ipv6helper=y
          EOF

          # 多文件系统支持:
          cat >> .config <<EOF
          CONFIG_PACKAGE_kmod-fs-nfs=y
          CONFIG_PACKAGE_kmod-fs-nfs-common=y
          CONFIG_PACKAGE_kmod-fs-nfs-v3=y
          CONFIG_PACKAGE_kmod-fs-nfs-v4=y
          CONFIG_PACKAGE_kmod-fs-ntfs=y
          CONFIG_PACKAGE_kmod-fs-squashfs=y
          EOF

          # USB3.0支持:
          cat >> .config <<EOF
          CONFIG_PACKAGE_kmod-usb-ohci=y
          CONFIG_PACKAGE_kmod-usb-ohci-pci=y
          CONFIG_PACKAGE_kmod-usb2=y
          CONFIG_PACKAGE_kmod-usb2-pci=y
          CONFIG_PACKAGE_kmod-usb3=y
          EOF
          
          # Target Images
          cat >> .config <<EOF
          CONFIG_TARGET_ROOTFS_INITRAMFS=y
          CONFIG_TARGET_INITRAMFS_COMPRESSION_LZMA=y
          CONFIG_EXTERNAL_CPIO=""
          EOF
          
          # Root filesystem images
          cat >> .config <<EOF
          CONFIG_TARGET_ROOTFS_SQUASHFS=y
          CONFIG_TARGET_SQUASHFS_BLOCK_SIZE=256
          CONFIG_TARGET_UBIFS_FREE_SPACE_FIXUP=y
          CONFIG_TARGET_UBIFS_JOURNAL_SIZE=""
          EOF
          
          # Global build settings
          cat >> .config <<EOF
          CONFIG_SIGNED_PACKAGES=y
          EOF
          
          # General build options
          cat >> .config <<EOF
          CONFIG_BUILD_PATENTED=y
          CONFIG_SHADOW_PASSWORDS=y
          EOF
          
          # Kernel build options
          cat >> .config <<EOF
          CONFIG_KERNEL_BUILD_USER=""
          CONFIG_KERNEL_BUILD_DOMAIN=""
          CONFIG_KERNEL_PRINTK=y
          CONFIG_KERNEL_SWAP=y
          CONFIG_KERNEL_DEBUG_FS=y
          CONFIG_KERNEL_KALLSYMS=y
          CONFIG_KERNEL_DEBUG_KERNEL=y
          CONFIG_KERNEL_DEBUG_INFO=y
          CONFIG_KERNEL_MAGIC_SYSRQ=y
          CONFIG_KERNEL_CRYPTO_DEV_QCE_ENABLE_ALL=y
          CONFIG_KERNEL_COREDUMP=y
          CONFIG_KERNEL_ELF_CORE=y
          CONFIG_KERNEL_PRINTK_TIME=y
          CONFIG_KERNEL_KEXEC=y
          CONFIG_KERNEL_PROC_VMCORE=y
          CONFIG_KERNEL_CRASH_DUMP=y
          CONFIG_KERNEL_DEVPTS_MULTIPLE_INSTANCES=y
          CONFIG_KERNEL_POSIX_MQUEUE=y
          CONFIG_KERNEL_IP_MROUTE=y
          CONFIG_KERNEL_IPV6=y
          CONFIG_KERNEL_IPV6_MULTIPLE_TABLES=y
          CONFIG_KERNEL_IPV6_SUBTREES=y
          CONFIG_KERNEL_IPV6_MROUTE=y
          EOF

          # Filesystem ACL and attr support options
          cat >> .config <<EOF
          CONFIG_KERNEL_SQUASHFS_FRAGMENT_CACHE_SIZE=3
          CONFIG_KERNEL_CC_OPTIMIZE_FOR_PERFORMANCE=y
          EOF
          
          # Package build options
          cat >> .config <<EOF
          CONFIG_IPV6=y
          EOF
          
          # Stripping options
          cat >> .config <<EOF
          CONFIG_USE_SSTRIP=y
          CONFIG_USE_UCLIBCXX=y
          EOF
          
          
          
          # 常用LuCI插件选择:
          cat >> .config <<EOF
          CONFIG_PACKAGE_luci-app-accesscontrol=y
          CONFIG_PACKAGE_luci-app-adbyby-plus=y
          CONFIG_PACKAGE_luci-app-arpbind=y
          CONFIG_PACKAGE_luci-app-autoreboot=y
          # CONFIG_PACKAGE_luci-app-aria2=y
          # CONFIG_PACKAGE_luci-app-baidupcs-web=y
          # CONFIG_PACKAGE_luci-app-docker=y
          CONFIG_PACKAGE_luci-app-ddns=y
          CONFIG_PACKAGE_luci-app-filetransfer=y
          CONFIG_PACKAGE_luci-app-firewall=y
          CONFIG_PACKAGE_luci-app-flowoffload=y
          CONFIG_PACKAGE_luci-app-frpc=y
          CONFIG_PACKAGE_luci-app-hd-idle=y
          # CONFIG_PACKAGE_luci-app-kodexplorer=y
          # CONFIG_PACKAGE_luci-app-minidlna=y
          # CONFIG_PACKAGE_luci-app-openvpn=y
          # CONFIG_PACKAGE_luci-app-openvpn-server=y
          # CONFIG_PACKAGE_luci-app-qbittorrent=y
          CONFIG_PACKAGE_luci-app-nlbwmon=y
          CONFIG_PACKAGE_luci-app-ramfree=y
          CONFIG_PACKAGE_luci-app-samba=y
          CONFIG_PACKAGE_luci-app-sqm=y
          CONFIG_PACKAGE_luci-app-ssr-plus=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Shadowsocks=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Trojan=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Kcptun=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Server=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Socks=y
          CONFIG_PACKAGE_luci-app-upnp=y
          CONFIG_PACKAGE_luci-app-vlmcsd=y
          CONFIG_PACKAGE_luci-app-vsftpd=y
          CONFIG_PACKAGE_luci-app-wifischedule=y
          CONFIG_PACKAGE_luci-app-ttyd=y
          CONFIG_PACKAGE_luci-app-wol=y
          CONFIG_PACKAGE_luci-app-zerotier=y
          EOF
          
          # Protocols
          cat >> .config <<EOF
          CONFIG_PACKAGE_luci-proto-ppp=y
          EOF
          
          # Libraries
          cat >> .config <<EOF
          CONFIG_PACKAGE_luci-lib-ip=y
          CONFIG_PACKAGE_luci-lib-jsonc=y
          CONFIG_PACKAGE_luci-lib-nixio=y
          EOF
          
          # Freifunk
          cat >> .config <<EOF
          CONFIG_PACKAGE_default-settings=y
          CONFIG_PACKAGE_luci-i18n-accesscontrol-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-adbyby-plus-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-arpbind-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-autoreboot-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-base-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-ddns-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-filetransfer-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-firewall-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-flowoffload-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-nlbwmon-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-ramfree-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-samba-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-upnp-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-vlmcsd-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-vsftpd-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-wifischedule-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-wol-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-zerotier-zh-cn=y
          EOF
          
          # Select postfix build options
          cat >> .config <<EOF
          CONFIG_POSTFIX_TLS=y
          CONFIG_POSTFIX_SASL=y
          CONFIG_POSTFIX_LDAP=y
          CONFIG_POSTFIX_CDB=y
          CONFIG_POSTFIX_SQLITE=y
          CONFIG_POSTFIX_PCRE=y
          EOF
          
          # File Transfer
          cat >> .config <<EOF
          CONFIG_PACKAGE_atftp=y
          CONFIG_PACKAGE_atftpd=y
          CONFIG_PACKAGE_vsftpd-alt=y
          CONFIG_VSFTPD_USE_UCI_SCRIPTS=y
          CONFIG_PACKAGE_wget=y
          EOF
          
          # Firewall
          cat >> .config <<EOF
          CONFIG_PACKAGE_iptables=y
          CONFIG_PACKAGE_iptables-mod-conntrack-extra=y
          CONFIG_PACKAGE_iptables-mod-fullconenat=y
          CONFIG_PACKAGE_iptables-mod-ipopt=y
          CONFIG_PACKAGE_iptables-mod-tproxy=y
          CONFIG_PACKAGE_miniupnpd=y
          EOF
          
          # IP Addresses and Names
          cat >> .config <<EOF
          CONFIG_PACKAGE_ddns-scripts=y
          CONFIG_PACKAGE_ddns-scripts_aliyun=y
          EOF
          
          # NeteaseMusic
          cat >> .config <<EOF
          CONFIG_PACKAGE_UnblockNeteaseMusic=y
          EOF
          
          # P2P
          cat >> .config <<EOF
          CONFIG_AMULE_CRYPTOPP_STATIC_LINKING=y
          EOF
          
          # Routing and Redirection
          cat >> .config <<EOF
          CONFIG_PACKAGE_ip-full=y
          CONFIG_PACKAGE_tc=y
          EOF
          
          # VPN
          cat >> .config <<EOF
          CONFIG_PACKAGE_zerotier=y
          EOF
          
          # Web Servers/Proxies
          cat >> .config <<EOF
          CONFIG_PACKAGE_pdnsd-alt=y
          CONFIG_PACKAGE_shadowsocks-libev-config=y
          CONFIG_PACKAGE_shadowsocks-libev-ss-redir=y
          CONFIG_PACKAGE_uhttpd=y
          CONFIG_PACKAGE_uhttpd-mod-ubus=y
          EOF
          
          # wireless
          cat >> .config <<EOF
          CONFIG_PACKAGE_wifischedule=y
          CONFIG_PACKAGE_adbyby=y
          CONFIG_PACKAGE_etherwake=y
          CONFIG_PACKAGE_hostapd-common=y
          CONFIG_PACKAGE_ipset=y
          CONFIG_PACKAGE_ipt2socks=y
          CONFIG_PACKAGE_iw=y
          CONFIG_PACKAGE_kcptun-client=y
          CONFIG_PACKAGE_libipset=y
          CONFIG_PACKAGE_nlbwmon=y
          CONFIG_PACKAGE_ppp=y
          CONFIG_PACKAGE_ppp-mod-pppoe=y
          CONFIG_PACKAGE_samba36-server=y
          CONFIG_PACKAGE_SAMBA_MAX_DEBUG_LEVEL=-1
          CONFIG_PACKAGE_shadowsocksr-libev-alt=y
          CONFIG_PACKAGE_shadowsocksr-libev-server=y
          CONFIG_PACKAGE_shadowsocksr-libev-ssr-local=y
          CONFIG_PACKAGE_trojan=y
          CONFIG_PACKAGE_uclient-fetch=y
          CONFIG_PACKAGE_v2ray=y
          CONFIG_PACKAGE_vlmcsd=y
          CONFIG_WPA_MSG_MIN_PRIORITY=3
          CONFIG_DRIVER_11N_SUPPORT=y
          CONFIG_DRIVER_11AC_SUPPORT=y
          CONFIG_DRIVER_11W_SUPPORT=y
          CONFIG_PACKAGE_wpad=y
          EOF
          
          # Filesystem
          cat >> .config <<EOF
          CONFIG_PACKAGE_ntfs-3g=y
          EOF
          
          # Shells
          cat >> .config <<EOF
          CONFIG_PACKAGE_bash=y
          EOF
          
          # database
          cat >> .config <<EOF
          CONFIG_PACKAGE_coremark=y
          CONFIG_PACKAGE_coreutils=y
          CONFIG_PACKAGE_coreutils-base64=y
          CONFIG_PACKAGE_coreutils-nohup=y
          CONFIG_PACKAGE_iwinfo=y
          CONFIG_PACKAGE_jshn=y
          CONFIG_PACKAGE_libjson-script=y
          CONFIG_PACKAGE_openssl-util=y
          CONFIG_PACKAGE_shellsync=y
          CONFIG_PACKAGE_ubi-utils=y
          
          
          CONFIG_PACKAGE_luci-app-webadmin=y
          CONFIG_PACKAGE_luci-app-wrtbwmon=y
          # EOF

          # LuCI主题:
          cat >> .config <<EOF
          CONFIG_PACKAGE_luci-theme-argon=y
          CONFIG_PACKAGE_luci-theme-netgear=y
          CONFIG_PACKAGE_luci-theme-bootstrap=y
          CONFIG_PACKAGE_luci-theme-material=y
          EOF
          
          # 取消编译VMware镜像以及镜像填充 (不要删除被缩进的注释符号):
          # cat >> .config <<EOF
          # # CONFIG_TARGET_IMAGES_PAD is not set
          # # CONFIG_VMDK_IMAGES is not set
          # EOF

          # 
          # ========================固件定制部分结束========================
          # 

          sed -i 's/^[ \t]*//g' ./.config
          make defconfig

      - name: Make download
        run: |
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: Compile firmware
        run: |
          echo -e "$(nproc) thread build."
          make -j$(nproc) V=s

      - name: Assemble artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          find ./bin/targets/ -name "*combined*img*" | xargs -i mv -f {} ./artifact/
          find ./bin/targets/ -name "*sysupgrade*bin*" | xargs -i mv -f {} ./artifact/

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt firmware
          path: ./artifact/
