#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
# 

name: OpenWrt-CI

on:
  schedule:
    - cron: 0 20 * * 5
  push:
    tags:
      - '*'

jobs:
  
  build_openwrt:
    
    name: Build OpenWrt and release
    runs-on: ubuntu-18.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          df -h

      - name: luci-app-clash
        run: |
          cd package
          mkdir luci-app-clash
          cd luci-app-clash
          git clone https://github.com/frainzy1477/luci-app-clash.git

      - name: Update feeds
        run: |
          sed -i 's/\"#src-git\"/\"src-git\"/g' ./feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Costom configure file
        run: |
          rm -f ./.config*
          touch ./.config

          cat >> .config <<EOF
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_64=y
          CONFIG_TARGET_x86_64_Generic=y
          CONFIG_AMULE_CRYPTOPP_STATIC_LINKING=y
          CONFIG_ATH10K_THERMAL=y
          CONFIG_EFI_IMAGES=y
          CONFIG_LIBMBEDTLS_HAVE_SSE2=y
          # CONFIG_OPENSSL_ENGINE_BUILTIN is not set
          CONFIG_PACKAGE_6in4=y
          CONFIG_PACKAGE_acme=y
          # CONFIG_PACKAGE_amule is not set
          CONFIG_PACKAGE_bash=y
          CONFIG_PACKAGE_blkid=y
          # CONFIG_PACKAGE_boost-chrono is not set
          CONFIG_PACKAGE_boost-date_time=y
          CONFIG_PACKAGE_boost-program_options=y
          # CONFIG_PACKAGE_boost-random is not set
          CONFIG_PACKAGE_btrfs-progs=y
          CONFIG_PACKAGE_collectd=y
          CONFIG_PACKAGE_collectd-mod-cpu=y
          CONFIG_PACKAGE_collectd-mod-interface=y
          CONFIG_PACKAGE_collectd-mod-iwinfo=y
          CONFIG_PACKAGE_collectd-mod-load=y
          CONFIG_PACKAGE_collectd-mod-memory=y
          CONFIG_PACKAGE_collectd-mod-network=y
          CONFIG_PACKAGE_collectd-mod-rrdtool=y
          CONFIG_PACKAGE_coreutils=y
          CONFIG_PACKAGE_coreutils-base64=y
          CONFIG_PACKAGE_coreutils-nohup=y
          CONFIG_PACKAGE_curl=y
          CONFIG_PACKAGE_dns2socks=y
          CONFIG_PACKAGE_frpc=y
          CONFIG_PACKAGE_grub2-efi=y
          # CONFIG_PACKAGE_icu is not set
          CONFIG_PACKAGE_ip6tables=y
          CONFIG_PACKAGE_ipt2socks=y
          CONFIG_PACKAGE_iptables-mod-conntrack-extra=y
          CONFIG_PACKAGE_iptables-mod-ipopt=y
          CONFIG_PACKAGE_iptables-mod-tproxy=y
          CONFIG_PACKAGE_ipv6helper=y
          CONFIG_PACKAGE_kcptun-client=y
          # CONFIG_PACKAGE_kmod-crypto-user is not set
          CONFIG_PACKAGE_kmod-gre=y
          CONFIG_PACKAGE_kmod-ifb=y
          CONFIG_PACKAGE_kmod-ip6tables=y
          CONFIG_PACKAGE_kmod-ipt-conntrack-extra=y
          CONFIG_PACKAGE_kmod-ipt-ipopt=y
          CONFIG_PACKAGE_kmod-ipt-nat6=y
          CONFIG_PACKAGE_kmod-ipt-tproxy=y
          CONFIG_PACKAGE_kmod-iptunnel=y
          CONFIG_PACKAGE_kmod-lib-crc32c=y
          CONFIG_PACKAGE_kmod-lib-raid6=y
          CONFIG_PACKAGE_kmod-lib-xor=y
          CONFIG_PACKAGE_kmod-md-mod=y
          CONFIG_PACKAGE_kmod-md-raid0=y
          CONFIG_PACKAGE_kmod-md-raid1=y
          CONFIG_PACKAGE_kmod-md-raid10=y
          CONFIG_PACKAGE_kmod-md-raid456=y
          CONFIG_PACKAGE_kmod-nf-ipt6=y
          CONFIG_PACKAGE_kmod-nf-nat6=y
          CONFIG_PACKAGE_kmod-nf-reject6=y
          CONFIG_PACKAGE_kmod-sched-cake=y
          CONFIG_PACKAGE_kmod-sched-core=y
          CONFIG_PACKAGE_kmod-sit=y
          # CONFIG_PACKAGE_kmod-sound-hda-codec-hdmi is not set
          # CONFIG_PACKAGE_kmod-sound-hda-intel is not set
          # CONFIG_PACKAGE_kmod-sound-i8x0 is not set
          CONFIG_PACKAGE_kmod-thermal=y
          CONFIG_PACKAGE_libattr=y
          # CONFIG_PACKAGE_libbfd is not set
          # CONFIG_PACKAGE_libcryptopp is not set
          # CONFIG_PACKAGE_libdb47 is not set
          # CONFIG_PACKAGE_libdouble-conversion is not set
          CONFIG_PACKAGE_libev=y
          # CONFIG_PACKAGE_libffi is not set
          CONFIG_PACKAGE_libltdl=y
          CONFIG_PACKAGE_libmbedtls=y
          CONFIG_PACKAGE_libmount=y
          CONFIG_PACKAGE_libnet-1.2.x=y
          CONFIG_PACKAGE_libopenssl-devcrypto=y
          CONFIG_PACKAGE_libpcap=y
          # CONFIG_PACKAGE_libpcre2-16 is not set
          # CONFIG_PACKAGE_libpng is not set
          CONFIG_PACKAGE_librrd1=y
          # CONFIG_PACKAGE_libupnp is not set
          # CONFIG_PACKAGE_libwxbase is not set
          # CONFIG_PACKAGE_libzstd is not set
          CONFIG_PACKAGE_lsblk=y
          CONFIG_PACKAGE_luci-app-acme=y
          # CONFIG_PACKAGE_luci-app-amule is not set
          CONFIG_PACKAGE_luci-app-clash=y
          CONFIG_PACKAGE_luci-app-diskman=y
          CONFIG_PACKAGE_luci-app-diskman_INCLUDE_btrfs_progs=y
          CONFIG_PACKAGE_luci-app-diskman_INCLUDE_kmod_md_linear=y
          CONFIG_PACKAGE_luci-app-diskman_INCLUDE_kmod_md_raid456=y
          CONFIG_PACKAGE_luci-app-diskman_INCLUDE_lsblk=y
          CONFIG_PACKAGE_luci-app-diskman_INCLUDE_mdadm=y
          CONFIG_PACKAGE_luci-app-frpc=y
          # CONFIG_PACKAGE_luci-app-openvpn-server is not set
          # CONFIG_PACKAGE_luci-app-qbittorrent is not set
          CONFIG_PACKAGE_luci-app-sqm=y
          CONFIG_PACKAGE_luci-app-statistics=y
          # CONFIG_PACKAGE_luci-app-xlnetacc is not set
          CONFIG_PACKAGE_luci-i18n-statistics-zh-cn=y
          CONFIG_PACKAGE_luci-proto-ipv6=y
          CONFIG_PACKAGE_luci-proto-relay=y
          CONFIG_PACKAGE_luci-theme-argon=y
          CONFIG_PACKAGE_luci-theme-material=y
          CONFIG_PACKAGE_mdadm=y
          CONFIG_PACKAGE_microsocks=y
          CONFIG_PACKAGE_odhcp6c=y
          CONFIG_PACKAGE_odhcp6c_ext_cer_id=0
          CONFIG_PACKAGE_odhcpd-ipv6only=y
          CONFIG_PACKAGE_odhcpd_ipv6only_ext_cer_id=0
          # CONFIG_PACKAGE_openvpn-easy-rsa is not set
          # CONFIG_PACKAGE_openvpn-openssl is not set
          CONFIG_PACKAGE_parted=y
          CONFIG_PACKAGE_pptpd=y
          CONFIG_PACKAGE_proxychains-ng=y
          # CONFIG_PACKAGE_python is not set
          # CONFIG_PACKAGE_python-base is not set
          # CONFIG_PACKAGE_python-codecs is not set
          # CONFIG_PACKAGE_python-compiler is not set
          # CONFIG_PACKAGE_python-ctypes is not set
          # CONFIG_PACKAGE_python-db is not set
          # CONFIG_PACKAGE_python-decimal is not set
          # CONFIG_PACKAGE_python-distutils is not set
          # CONFIG_PACKAGE_python-email is not set
          # CONFIG_PACKAGE_python-gdbm is not set
          # CONFIG_PACKAGE_python-light is not set
          # CONFIG_PACKAGE_python-logging is not set
          # CONFIG_PACKAGE_python-multiprocessing is not set
          # CONFIG_PACKAGE_python-ncurses is not set
          # CONFIG_PACKAGE_python-openssl is not set
          # CONFIG_PACKAGE_python-pydoc is not set
          # CONFIG_PACKAGE_python-sqlite3 is not set
          # CONFIG_PACKAGE_python-unittest is not set
          # CONFIG_PACKAGE_python-xml is not set
          # CONFIG_PACKAGE_qBittorrent is not set
          # CONFIG_PACKAGE_qt5-core is not set
          # CONFIG_PACKAGE_qt5-network is not set
          # CONFIG_PACKAGE_qt5-xml is not set
          # CONFIG_PACKAGE_rblibtorrent is not set
          CONFIG_PACKAGE_redsocks2=y
          CONFIG_PACKAGE_relayd=y
          CONFIG_PACKAGE_rrdtool1=y
          CONFIG_PACKAGE_shadowsocks-libev-ss-local=y
          CONFIG_PACKAGE_shadowsocks-libev-ss-redir=y
          CONFIG_PACKAGE_shadowsocksr-libev-alt=y
          CONFIG_PACKAGE_shadowsocksr-libev-server=y
          CONFIG_PACKAGE_shadowsocksr-libev-ssr-local=y
          CONFIG_PACKAGE_simple-obfs=y
          CONFIG_PACKAGE_smartmontools=y
          CONFIG_PACKAGE_socat=y
          CONFIG_PACKAGE_sqm-scripts=y
          CONFIG_PACKAGE_srelay=y
          CONFIG_PACKAGE_tc=y
          CONFIG_PACKAGE_tcpping=y
          CONFIG_PACKAGE_trojan=y
          CONFIG_PACKAGE_uclibcxx=y
          CONFIG_PACKAGE_v2ray=y
          CONFIG_PACKAGE_v2ray-plugin=y
          # CONFIG_TARGET_IMAGES_PAD is not set
          CONFIG_V2RAY_COMPRESS_UPX=y
          CONFIG_V2RAY_DISABLE_NONE=y
          CONFIG_V2RAY_EXCLUDE_ASSETS=y
          CONFIG_V2RAY_EXCLUDE_V2CTL=y
          CONFIG_V2RAY_JSON_INTERNAL=y
          # CONFIG_VMDK_IMAGES is not set
          EOF

          sed -i 's/^[ \t]*//g' ./.config
          make defconfig

      - name: Make download
        run: |
          make download -j8
          find dl -size -1024c -exec rm -f {} \;

      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin
          
      - name: Prepare artifact
        run: find ./bin/targets/ -type d -name "packages" | xargs rm -rf {}

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt_firmware
          path: ./bin/targets/
          
