name: Caching with npm

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # 下载文件
    - name: Cache openwrt dl
      uses: actions/cache@master
      env:
        cache-name: cache-openwrt-dl
      with:
        path: ./dl # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-stable-${{ env.cache-name }}-v2
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-${{ env.cache-name }}
          ${{ runner.os }}-

    # 工具链
    - name: Cache openwrt staging
      uses: actions/cache@master
      env:
        cache-name-staging: cache-openwrt-stagingd-dir
      with:
        path: ./staging_dir
        key: ${{ runner.os }}-stable-${{ env.cache-name-staging }}-v2
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name-staging }}-
          ${{ runner.os }}-build-${{ env.cache-name-staging }}
          ${{ runner.os }}-

    # 更新系统，安装必须文件
    - name: Space cleanup
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi `docker images -q`
        #sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
        #sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* 
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
        #sudo -E apt-get -y autoremove --purge
        #sudo -E apt-get clean
        df -h
        
    - name: Update feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        df -h
        
    # 自定义配置
    - name: Generate configuration file
      run: |
        cp ./makeconfig.d/x86_64.config ./.config
        echo "defconfig start"
        make defconfig
        
    # 下载必要
    - name: Make download
      run: |
        make download -j8
        find ./dl/ -size -1024c -exec rm -f {} \;
        df -h

    - name: Compile firmware
      run: |
        df -h
        make -j$(nproc) || make -j8 V=s
        echo "======================="
        echo "Space usage:"
        echo "======================="
        df -h
        echo "======================="
        du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
        du -h --max-depth=1 ./build_dir
        du -h --max-depth=1 ./bin

    - name: Prepare artifact
      run: |
        find ./bin/targets/ -type d -name "packages" | xargs rm -rf {}
        find ./bin/targets/ -name "openwrt-x86-64-rootfs-squashfs.img.gz" | xargs rm -rf {}
        
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt firmware
        path: ./bin/targets/
