#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
# Narizgnaw：非常感谢KFERMercer大佬提供的OpenWrt-CI。

name: 云编译

on:
  push:
    branches: 
      - master
  release:
      types: [published]
  watch:
    types: [started]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 校验本地文件
        uses: actions/checkout@master
        with:
          ref: master

      - name: 安装编译环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
      - name: 清理系统环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          echo "Deleting files, please wait ..."
          sudo rm -rf \
            /usr/share/dotnet \
            /etc/mysql \
            /etc/php
          sudo -E apt-get -y purge \
            azure-cli \
            ghc* \
            zulu* \
            hhvm \
            llvm* \
            firefox \
            google* \
            dotnet* \
            powershell \
            openjdk* \
            mysql* \
            php*
      - name: 更新软件列表
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get update
      - name: 安装编译所需环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
      - name: 进行安装后的清理
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
      - name: 构建自定义文件结构
        run: |
          cd package/lean
          git clone https://github.com/openwrt-develop/luci-theme-atmaterial.git
          git clone https://github.com/KFERMercer/luci-app-serverchan
          git clone https://github.com/Ameykyl/luci-app-koolproxyR
          git clone https://github.com/destan19/OpenAppFilter.git
      - name: 构建编译扩展环境
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: 自定义
        run: |
          sed -i 's/192.168.1.1/192.168.2.1/g' package/base-files/files/bin/config_generate
          sed -i 's/name="luci_username" value="<%=duser%>"/name="luci_username"/g' feeds/luci/modules/luci-base/luasrc/view/sysauth.htm
          sed -i "s/'luci_password'/'luci_username'/g" feeds/luci/modules/luci-base/luasrc/view/sysauth.htm
          sed -i 's/IMG_PREFIX:=$(VERSION_DIST_SANITIZED)/IMG_PREFIX:=[$(shell date +%Y%m%d)]-$(VERSION_DIST_SANITIZED)/g' include/image.mk
      - name: 导入自定义配置
        run: |
          rm -f ./.config*
          touch ./.config
          # 编译x64固件:
          cat >> .config <<EOF
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_64=y
          CONFIG_TARGET_x86_64_Generic=y
          # CONFIG_DRIVER_11AC_SUPPORT is not set
          # CONFIG_DRIVER_11N_SUPPORT is not set
          # CONFIG_DRIVER_11W_SUPPORT is not set
          CONFIG_GNUTLS_ALPN=y
          CONFIG_GNUTLS_ANON=y
          CONFIG_GNUTLS_DTLS_SRTP=y
          CONFIG_GNUTLS_HEARTBEAT=y
          CONFIG_GNUTLS_OCSP=y
          CONFIG_GNUTLS_PSK=y
          CONFIG_LIBCURL_COOKIES=y
          CONFIG_LIBCURL_FILE=y
          CONFIG_LIBCURL_FTP=y
          CONFIG_LIBCURL_HTTP=y
          CONFIG_LIBCURL_NO_SMB="!"
          CONFIG_LIBCURL_OPENSSL=y
          CONFIG_LIBCURL_PROXY=y
          CONFIG_OCSERV_HTTP_PARSER=y
          CONFIG_OCSERV_PAM=y
          CONFIG_OCSERV_PROTOBUF=y
          CONFIG_OCSERV_RADIUS=y
          CONFIG_OCSERV_SECCOMP=y
          CONFIG_PACKAGE_6in4=y
          # CONFIG_PACKAGE_adbyby is not set
          # CONFIG_PACKAGE_alsa-lib is not set
          # CONFIG_PACKAGE_alsa-utils is not set
          CONFIG_PACKAGE_appfilter=y
          # CONFIG_PACKAGE_ath10k-firmware-qca9888 is not set
          # CONFIG_PACKAGE_ath10k-firmware-qca988x is not set
          # CONFIG_PACKAGE_ath10k-firmware-qca9984 is not set
          # CONFIG_PACKAGE_ath9k-htc-firmware is not set
          CONFIG_PACKAGE_attendedsysupgrade-common=y
          # CONFIG_PACKAGE_automount is not set
          # CONFIG_PACKAGE_autosamba is not set
          CONFIG_PACKAGE_autossh=y
          # CONFIG_PACKAGE_boost-chrono is not set
          # CONFIG_PACKAGE_boost-random is not set
          # CONFIG_PACKAGE_brcmfmac-firmware-43602a1-pcie is not set
          CONFIG_PACKAGE_ca-bundle=y
          CONFIG_PACKAGE_certtool=y
          CONFIG_PACKAGE_cgi-io=y
          CONFIG_PACKAGE_collectd=y
          CONFIG_PACKAGE_collectd-mod-cpu=y
          CONFIG_PACKAGE_collectd-mod-interface=y
          CONFIG_PACKAGE_collectd-mod-iwinfo=y
          CONFIG_PACKAGE_collectd-mod-load=y
          CONFIG_PACKAGE_collectd-mod-memory=y
          CONFIG_PACKAGE_collectd-mod-network=y
          CONFIG_PACKAGE_collectd-mod-rrdtool=y
          CONFIG_PACKAGE_curl=y
          # CONFIG_PACKAGE_ddns-scripts is not set
          # CONFIG_PACKAGE_ddns-scripts_aliyun is not set
          CONFIG_PACKAGE_dnsmasq_full_auth=y
          CONFIG_PACKAGE_dnsmasq_full_broken_rtc=y
          CONFIG_PACKAGE_dnsmasq_full_conntrack=y
          CONFIG_PACKAGE_dnsmasq_full_dhcpv6=y
          CONFIG_PACKAGE_dnsmasq_full_dnssec=y
          CONFIG_PACKAGE_dnsmasq_full_noid=y
          CONFIG_PACKAGE_fuse-utils=y
          CONFIG_PACKAGE_glib2=y
          # CONFIG_PACKAGE_hostapd-common is not set
          CONFIG_PACKAGE_hostip=y
          CONFIG_PACKAGE_iftop=y
          CONFIG_PACKAGE_ip6tables=y
          CONFIG_PACKAGE_iptables-mod-nat-extra=y
          CONFIG_PACKAGE_iputils-arping=y
          CONFIG_PACKAGE_ipv6helper=y
          # CONFIG_PACKAGE_iw is not set
          CONFIG_PACKAGE_kcptun-client=y
          # CONFIG_PACKAGE_kmod-ath is not set
          # CONFIG_PACKAGE_kmod-ath10k is not set
          # CONFIG_PACKAGE_kmod-ath5k is not set
          # CONFIG_PACKAGE_kmod-ath9k is not set
          # CONFIG_PACKAGE_kmod-ath9k-htc is not set
          CONFIG_PACKAGE_kmod-br-netfilter=y
          # CONFIG_PACKAGE_kmod-button-hotplug is not set
          # CONFIG_PACKAGE_kmod-cfg80211 is not set
          CONFIG_PACKAGE_kmod-dnsresolver=y
          # CONFIG_PACKAGE_kmod-fs-exfat is not set
          CONFIG_PACKAGE_kmod-fs-nfs=y
          CONFIG_PACKAGE_kmod-fs-nfs-common=y
          CONFIG_PACKAGE_kmod-fs-nfs-v3=y
          CONFIG_PACKAGE_kmod-fs-nfs-v4=y
          # CONFIG_PACKAGE_kmod-hid is not set
          # CONFIG_PACKAGE_kmod-hid-generic is not set
          # CONFIG_PACKAGE_kmod-input-core is not set
          # CONFIG_PACKAGE_kmod-input-evdev is not set
          CONFIG_PACKAGE_kmod-ip6tables-extra=y
          CONFIG_PACKAGE_kmod-ipt-account=y
          CONFIG_PACKAGE_kmod-ipt-chaos=y
          CONFIG_PACKAGE_kmod-ipt-checksum=y
          CONFIG_PACKAGE_kmod-ipt-cluster=y
          CONFIG_PACKAGE_kmod-ipt-clusterip=y
          CONFIG_PACKAGE_kmod-ipt-compat-xtables=y
          CONFIG_PACKAGE_kmod-ipt-condition=y
          CONFIG_PACKAGE_kmod-ipt-conntrack-label=y
          CONFIG_PACKAGE_kmod-ipt-debug=y
          CONFIG_PACKAGE_kmod-ipt-delude=y
          CONFIG_PACKAGE_kmod-ipt-extra=y
          CONFIG_PACKAGE_kmod-ipt-filter=y
          CONFIG_PACKAGE_kmod-ipt-fuzzy=y
          CONFIG_PACKAGE_kmod-ipt-geoip=y
          CONFIG_PACKAGE_kmod-ipt-hashlimit=y
          CONFIG_PACKAGE_kmod-ipt-iface=y
          CONFIG_PACKAGE_kmod-ipt-iprange=y
          CONFIG_PACKAGE_kmod-ipt-ipv4options=y
          CONFIG_PACKAGE_kmod-ipt-length2=y
          CONFIG_PACKAGE_kmod-ipt-logmark=y
          CONFIG_PACKAGE_kmod-ipt-lscan=y
          CONFIG_PACKAGE_kmod-ipt-lua=y
          CONFIG_PACKAGE_kmod-ipt-nat-extra=y
          CONFIG_PACKAGE_kmod-ipt-nat6=y
          CONFIG_PACKAGE_kmod-ipt-nathelper-rtsp=y
          CONFIG_PACKAGE_kmod-ipt-nflog=y
          CONFIG_PACKAGE_kmod-ipt-nfqueue=y
          CONFIG_PACKAGE_kmod-ipt-physdev=y
          CONFIG_PACKAGE_kmod-ipt-psd=y
          CONFIG_PACKAGE_kmod-ipt-quota2=y
          CONFIG_PACKAGE_kmod-ipt-raw6=y
          CONFIG_PACKAGE_kmod-ipt-rpfilter=y
          CONFIG_PACKAGE_kmod-ipt-sysrq=y
          CONFIG_PACKAGE_kmod-ipt-tarpit=y
          CONFIG_PACKAGE_kmod-ipt-tee=y
          # CONFIG_PACKAGE_kmod-mac80211 is not set
          CONFIG_PACKAGE_kmod-macvlan=y
          CONFIG_PACKAGE_kmod-nf-nat6=y
          CONFIG_PACKAGE_kmod-nfnetlink-log=y
          CONFIG_PACKAGE_kmod-nfnetlink-queue=y
          CONFIG_PACKAGE_kmod-nls-cp936=y
          CONFIG_PACKAGE_kmod-oaf=y
          # CONFIG_PACKAGE_kmod-rt2800-usb is not set
          # CONFIG_PACKAGE_kmod-rt2x00-lib is not set
          CONFIG_PACKAGE_kmod-sched-connmark=y
          CONFIG_PACKAGE_kmod-sit=y
          # CONFIG_PACKAGE_kmod-sound-core is not set
          CONFIG_PACKAGE_kmod-udptunnel4=y
          CONFIG_PACKAGE_kmod-udptunnel6=y
          # CONFIG_PACKAGE_kmod-usb-hid is not set
          # CONFIG_PACKAGE_kmod-usb-net is not set
          # CONFIG_PACKAGE_kmod-usb-storage-extras is not set
          CONFIG_PACKAGE_kmod-wireguard=y
          # CONFIG_PACKAGE_libatomic is not set
          CONFIG_PACKAGE_libattr=y
          CONFIG_PACKAGE_libcap=y
          CONFIG_PACKAGE_libcares=y
          CONFIG_PACKAGE_libcurl=y
          # CONFIG_PACKAGE_libdb47 is not set
          # CONFIG_PACKAGE_libdouble-conversion is not set
          # CONFIG_PACKAGE_libexpat is not set
          CONFIG_PACKAGE_libfuse=y
          # CONFIG_PACKAGE_libgdbm is not set
          CONFIG_PACKAGE_libgnutls=y
          CONFIG_PACKAGE_libltdl=y
          CONFIG_PACKAGE_liblzma=y
          CONFIG_PACKAGE_libnetfilter-conntrack=y
          CONFIG_PACKAGE_libnettle=y
          CONFIG_PACKAGE_libnfnetlink=y
          CONFIG_PACKAGE_libpam=y
          CONFIG_PACKAGE_libpcap=y
          # CONFIG_PACKAGE_libpcre2-16 is not set
          CONFIG_PACKAGE_libprotobuf-c=y
          CONFIG_PACKAGE_libradcli=y
          CONFIG_PACKAGE_librrd1=y
          CONFIG_PACKAGE_libseccomp=y
          # CONFIG_PACKAGE_libsqlite3 is not set
          CONFIG_PACKAGE_libtirpc=y
          CONFIG_PACKAGE_libunrar=y
          CONFIG_PACKAGE_libwebsockets-full=y
          # CONFIG_PACKAGE_libxml2 is not set
          # CONFIG_PACKAGE_luci-app-adbyby-plus is not set
          CONFIG_PACKAGE_luci-app-advanced-reboot=y
          CONFIG_PACKAGE_luci-app-attendedsysupgrade=y
          # CONFIG_PACKAGE_luci-app-ddns is not set
          CONFIG_PACKAGE_luci-app-familycloud=y
          # CONFIG_PACKAGE_luci-app-ipsec-vpnd is not set
          CONFIG_PACKAGE_luci-app-koolproxyR=y
          CONFIG_PACKAGE_luci-app-mwan3=y
          CONFIG_PACKAGE_luci-app-mwan3helper=y
          CONFIG_PACKAGE_luci-app-netdata=y
          CONFIG_PACKAGE_luci-app-oaf=y
          CONFIG_PACKAGE_luci-app-ocserv=y
          # CONFIG_PACKAGE_luci-app-pptp-server is not set
          # CONFIG_PACKAGE_luci-app-qbittorrent is not set
          CONFIG_PACKAGE_luci-app-qos=y
          # CONFIG_PACKAGE_luci-app-samba is not set
          CONFIG_PACKAGE_luci-app-serverchan=y
          CONFIG_PACKAGE_luci-app-smartdns=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Kcptun=y
          CONFIG_PACKAGE_luci-app-statistics=y
          CONFIG_PACKAGE_luci-app-syncdial=y
          CONFIG_PACKAGE_luci-app-tinyproxy=y
          CONFIG_PACKAGE_luci-app-ttyd=y
          CONFIG_PACKAGE_luci-app-udpxy=y
          # CONFIG_PACKAGE_luci-app-vsftpd is not set
          CONFIG_PACKAGE_luci-app-watchcat=y
          CONFIG_PACKAGE_luci-app-wireguard=y
          CONFIG_PACKAGE_luci-app-wrtbwmon=y
          # CONFIG_PACKAGE_luci-app-xlnetacc is not set
          # CONFIG_PACKAGE_luci-app-zerotier is not set
          CONFIG_PACKAGE_luci-i18n-advanced-reboot-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-mwan3-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-mwan3helper-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-netdata-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-oaf-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-qos-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-smartdns-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-statistics-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-tinyproxy-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-ttyd-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-watchcat-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-wireguard-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-wrtbwmon-zh-cn=y
          CONFIG_PACKAGE_luci-lib-httpprotoutils=y
          CONFIG_PACKAGE_luci-proto-ipv6=y
          CONFIG_PACKAGE_luci-proto-wireguard=y
          CONFIG_PACKAGE_luci-theme-argon=y
          CONFIG_PACKAGE_luci-theme-atmaterial=y
          CONFIG_PACKAGE_luci-theme-netgear=y
          CONFIG_PACKAGE_mwan3=y
          CONFIG_PACKAGE_netdata=y
          CONFIG_PACKAGE_ocserv=y
          CONFIG_PACKAGE_odhcp6c=y
          CONFIG_PACKAGE_odhcp6c_ext_cer_id=0
          CONFIG_PACKAGE_odhcpd-ipv6only=y
          CONFIG_PACKAGE_odhcpd_ipv6only_ext_cer_id=0
          CONFIG_PACKAGE_open-vm-tools=y
          # CONFIG_PACKAGE_pptpd is not set
          # CONFIG_PACKAGE_python is not set
          # CONFIG_PACKAGE_python-base is not set
          # CONFIG_PACKAGE_python-codecs is not set
          # CONFIG_PACKAGE_python-compiler is not set
          # CONFIG_PACKAGE_python-ctypes is not set
          # CONFIG_PACKAGE_python-db is not set
          # CONFIG_PACKAGE_python-decimal is not set
          # CONFIG_PACKAGE_python-distutils is not set
          # CONFIG_PACKAGE_python-email is not set
          # CONFIG_PACKAGE_python-gdbm is not set
          # CONFIG_PACKAGE_python-light is not set
          # CONFIG_PACKAGE_python-logging is not set
          # CONFIG_PACKAGE_python-multiprocessing is not set
          # CONFIG_PACKAGE_python-ncurses is not set
          # CONFIG_PACKAGE_python-openssl is not set
          # CONFIG_PACKAGE_python-pydoc is not set
          # CONFIG_PACKAGE_python-sqlite3 is not set
          # CONFIG_PACKAGE_python-unittest is not set
          # CONFIG_PACKAGE_python-xml is not set
          # CONFIG_PACKAGE_qBittorrent is not set
          CONFIG_PACKAGE_qos-scripts=y
          # CONFIG_PACKAGE_qt5-core is not set
          # CONFIG_PACKAGE_qt5-network is not set
          # CONFIG_PACKAGE_qt5-xml is not set
          # CONFIG_PACKAGE_rblibtorrent is not set
          CONFIG_PACKAGE_resolveip=y
          CONFIG_PACKAGE_rpcd-mod-rpcsys=y
          CONFIG_PACKAGE_rrdtool1=y
          # CONFIG_PACKAGE_rt2800-usb-firmware is not set
          # CONFIG_PACKAGE_samba36-server is not set
          CONFIG_PACKAGE_screen=y
          CONFIG_PACKAGE_shadowsocks-libev-ss-local=y
          CONFIG_PACKAGE_shadowsocks-libev-ss-rules=y
          CONFIG_PACKAGE_shadowsocks-libev-ss-server=y
          CONFIG_PACKAGE_shadowsocks-libev-ss-tunnel=y
          CONFIG_PACKAGE_smartdns=y
          CONFIG_PACKAGE_sshfs=y
          # CONFIG_PACKAGE_strongswan-minimal is not set
          # CONFIG_PACKAGE_strongswan-mod-xauth-generic is not set
          CONFIG_PACKAGE_tcpdump=y
          CONFIG_PACKAGE_tinyproxy=y
          CONFIG_PACKAGE_ttyd=y
          CONFIG_PACKAGE_uclibcxx=y
          CONFIG_PACKAGE_udpxy=y
          CONFIG_PACKAGE_vim-fuller=y
          # CONFIG_PACKAGE_vsftpd-alt is not set
          CONFIG_PACKAGE_watchcat=y
          CONFIG_PACKAGE_wireguard-tools=y
          # CONFIG_PACKAGE_wireless-regdb is not set
          # CONFIG_PACKAGE_wpad is not set
          # CONFIG_PACKAGE_zerotier is not set
          # CONFIG_PACKAGE_NTFS-3G_USE_LIBFUSE is not set
          CONFIG_PACKAGE_iptables-mod-ipsec=y
          CONFIG_PACKAGE_kmod-crypto-acompress=y
          CONFIG_PACKAGE_kmod-crypto-cbc=y
          CONFIG_PACKAGE_kmod-crypto-crc32c=y
          CONFIG_PACKAGE_kmod-crypto-deflate=y
          CONFIG_PACKAGE_kmod-crypto-des=y
          CONFIG_PACKAGE_kmod-crypto-echainiv=y
          CONFIG_PACKAGE_kmod-crypto-hmac=y
          CONFIG_PACKAGE_kmod-crypto-iv=y
          CONFIG_PACKAGE_kmod-crypto-md5=y
          CONFIG_PACKAGE_kmod-crypto-rng=y
          CONFIG_PACKAGE_kmod-crypto-sha256=y
          CONFIG_PACKAGE_kmod-crypto-wq=y
          CONFIG_PACKAGE_kmod-fs-ext4=y
          CONFIG_PACKAGE_kmod-fs-vfat=y
          CONFIG_PACKAGE_kmod-gre=y
          # CONFIG_PACKAGE_kmod-ip-vti is not set
          # CONFIG_PACKAGE_kmod-ip6-vti is not set
          CONFIG_PACKAGE_kmod-ipsec=y
          CONFIG_PACKAGE_kmod-ipsec4=y
          CONFIG_PACKAGE_kmod-ipsec6=y
          CONFIG_PACKAGE_kmod-ipt-ipsec=y
          CONFIG_PACKAGE_kmod-iptunnel6=y
          CONFIG_PACKAGE_kmod-lib-crc16=y
          CONFIG_PACKAGE_kmod-lib-zlib-deflate=y
          CONFIG_PACKAGE_kmod-lib-zlib-inflate=y
          CONFIG_PACKAGE_kmod-nls-cp437=y
          CONFIG_PACKAGE_kmod-nls-iso8859-1=y
          CONFIG_PACKAGE_kmod-nls-utf8=y
          CONFIG_PACKAGE_kmod-scsi-core=y
          CONFIG_PACKAGE_kmod-usb-core=y
          CONFIG_PACKAGE_kmod-usb-storage=y
          # CONFIG_PACKAGE_kmod-xfrm-interface is not set
          CONFIG_PACKAGE_libbz2=y
          CONFIG_PACKAGE_libminiupnpc=y
          CONFIG_PACKAGE_libnatpmp=y
          CONFIG_PACKAGE_ntfs-3g=y
          CONFIG_PACKAGE_strongswan=y
          CONFIG_PACKAGE_strongswan-charon=y
          CONFIG_PACKAGE_strongswan-ipsec=y
          CONFIG_PACKAGE_strongswan-mod-aes=y
          CONFIG_PACKAGE_strongswan-mod-gmp=y
          CONFIG_PACKAGE_strongswan-mod-hmac=y
          CONFIG_PACKAGE_strongswan-mod-kernel-netlink=y
          CONFIG_PACKAGE_strongswan-mod-nonce=y
          CONFIG_PACKAGE_strongswan-mod-pubkey=y
          CONFIG_PACKAGE_strongswan-mod-random=y
          CONFIG_PACKAGE_strongswan-mod-sha1=y
          CONFIG_PACKAGE_strongswan-mod-socket-default=y
          CONFIG_PACKAGE_strongswan-mod-stroke=y
          CONFIG_PACKAGE_strongswan-mod-updown=y
          CONFIG_PACKAGE_strongswan-mod-x509=y
          CONFIG_PACKAGE_strongswan-mod-xcbc=y
          CONFIG_STRONGSWAN_ROUTING_TABLE="220"
          CONFIG_STRONGSWAN_ROUTING_TABLE_PRIO="220"
          EOF
          sed -i 's/^[ \t]*//g' ./.config
          make defconfig
#      - name: SSH 连接到 Actions
#        uses: P3TERX/debugger-action@master
      - name: 下载编译所需源码
        run: |
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;
      - name: 进行固件编译
        run: |
          echo -e "$(nproc) thread build."
          make -j$(nproc) V=s
          
      - name: 清理不必要的文件
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          find ./bin/targets/ -name "*combined*img*" | xargs -i mv -f {} ./artifact/
          find ./bin/targets/ -name "*combined*vmdk*" | xargs -i mv -f {} ./artifact/
          find ./bin/targets/ -name "*sysupgrade*bin*" | xargs -i mv -f {} ./artifact/
          find ./bin/targets/ -name "config.seed" | xargs -i mv -f {} ./artifact/
      - name : 上传固件
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt firmware
          path: ./artifact/
