name: Caching with npm

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # 下载文件
    - name: Cache openwrt dl
      uses: actions/cache@v1
      env:
        cache-name: cache-openwrt-dl
      with:
        path: ./dl # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    # 工具链
    - name: Cache openwrt staging
      uses: actions/cache@v1
      env:
        cache-name: cache-openwrt-staging
      with:
        path: ./staging_dir # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
          
    # 更新系统，安装必须文件
    - name: Space cleanup
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
        df -h
        
    - name: Update feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        df -h
        
    # 自定义配置
    - name: Generate configuration file
      run: |
        cp ./makeconfig.d/x86_64.config ./.config
        make defconfig
        
    # 下载必要
    - name: Make download
      run: |
        make download -j8
        find ./dl/ -size -1024c -exec rm -f {} \;
        df -h
        

