#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: OpenWrt-CI

on:
  push:
    branches: 
      - master
  schedule:
    - cron: 0 0 * * 1
  # release:
  #   types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

          # sudo mkdir -p -m 777 /mnt/openwrt/bin /mnt/openwrt/build_dir/host /mnt/openwrt/build_dir/hostpkg /mnt/openwrt/dl /mnt/openwrt/feeds /mnt/openwrt/staging_dir
          # ln -s /mnt/openwrt/bin ./bin
          # mkdir -p ./build_dir/host && ln -s /mnt/openwrt/build_dir/host ./build_dir/host
          # mkdir -p ./build_dir/host && ln -s /mnt/openwrt/build_dir/hostpkg ./build_dir/hostpkg
          # ln -s /mnt/openwrt/dl ./dl
          # ln -s /mnt/openwrt/feeds ./feeds
          # ln -s /mnt/openwrt/staging_dir ./staging_dir

          df -h

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate configuration file
        run: |
          rm -f ./.config*
          touch ./.config
          # Newifi3固件配置:
          cat >> .config <<EOF
                    CONFIG_TARGET_ramips=y
          CONFIG_TARGET_ramips_mt7621=y
          CONFIG_TARGET_ramips_mt7621_DEVICE_d-team_newifi-d2=y
          CONFIG_PACKAGE_6in4=y
          CONFIG_PACKAGE_ip6tables=y
          CONFIG_PACKAGE_ipv6helper=y
          CONFIG_PACKAGE_kmod-ip6tables=y
          CONFIG_PACKAGE_kmod-ipt-nat6=y
          CONFIG_PACKAGE_kmod-iptunnel=y
          CONFIG_PACKAGE_kmod-iptunnel4=y
          CONFIG_PACKAGE_kmod-nf-ipt6=y
          CONFIG_PACKAGE_kmod-nf-nat6=y
          CONFIG_PACKAGE_kmod-nf-reject6=y
          CONFIG_PACKAGE_kmod-sit=y
          CONFIG_PACKAGE_libbz2=y
          CONFIG_PACKAGE_libdb47=y
          CONFIG_PACKAGE_libexpat=y
          CONFIG_PACKAGE_libffi=y
          CONFIG_PACKAGE_libgdbm=y
          CONFIG_PACKAGE_libncurses=y
          CONFIG_PACKAGE_libsqlite3=y
          CONFIG_PACKAGE_libxml2=y
          CONFIG_PACKAGE_luci-app-ssrserver-python=y
          # CONFIG_PACKAGE_luci-app-unblockmusic is not set
          CONFIG_PACKAGE_luci-app-v2ray-server=y
          # CONFIG_PACKAGE_luci-app-vsftpd is not set
          CONFIG_PACKAGE_luci-i18n-ssrserver-python-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-v2ray-server-zh-cn=y
          CONFIG_PACKAGE_luci-proto-ipv6=y
          CONFIG_PACKAGE_luci-theme-netgear=y
          CONFIG_PACKAGE_odhcp6c=y
          CONFIG_PACKAGE_odhcp6c_ext_cer_id=0
          CONFIG_PACKAGE_odhcpd-ipv6only=y
          CONFIG_PACKAGE_odhcpd_ipv6only_ext_cer_id=0
          CONFIG_PACKAGE_python=y
          CONFIG_PACKAGE_python-base=y
          CONFIG_PACKAGE_python-codecs=y
          CONFIG_PACKAGE_python-compiler=y
          CONFIG_PACKAGE_python-ctypes=y
          CONFIG_PACKAGE_python-db=y
          CONFIG_PACKAGE_python-decimal=y
          CONFIG_PACKAGE_python-distutils=y
          CONFIG_PACKAGE_python-email=y
          CONFIG_PACKAGE_python-gdbm=y
          CONFIG_PACKAGE_python-light=y
          CONFIG_PACKAGE_python-logging=y
          CONFIG_PACKAGE_python-multiprocessing=y
          CONFIG_PACKAGE_python-ncurses=y
          CONFIG_PACKAGE_python-openssl=y
          CONFIG_PACKAGE_python-pydoc=y
          CONFIG_PACKAGE_python-sqlite3=y
          CONFIG_PACKAGE_python-unittest=y
          CONFIG_PACKAGE_python-xml=y
          CONFIG_PACKAGE_terminfo=y
          CONFIG_PACKAGE_v2ray=y
          # CONFIG_PACKAGE_vsftpd-alt is not set
          CONFIG_PACKAGE_watchcat=y
          CONFIG_SQLITE_FTS3=y
          CONFIG_SQLITE_RTREE=y
          CONFIG_V2RAY_COMPRESS_UPX=y
          CONFIG_V2RAY_DISABLE_NONE=y
          CONFIG_V2RAY_EXCLUDE_ASSETS=y
          CONFIG_V2RAY_EXCLUDE_V2CTL=y
          CONFIG_V2RAY_JSON_INTERNAL=y
          EOF
          sed -i 's/^[ \t]*//g' ./.config
          make defconfig

      - name: Make download
        run: |
          make download -j8
          find ./dl/ -size -1024c -exec rm -f {} \;
          df -h

      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin

      - name: Prepare artifact
        run: find ./bin/targets/ -type d -name "packages" | xargs rm -rf {}

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt firmware
          path: ./bin/targets/
