name: Caching with npm

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: ./dl # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Update feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
    - name: Generate configuration file
      run: |
        cp ./makeconfig.d/x86_64.config ./.config
        make defconfig
    - name: Make download
      run: |
        make download -j8
        find ./dl/ -size -1024c -exec rm -f {} \;
        df -h
