name: Sync Fork

on:
  schedule:
    - cron: '00 13 * * 4' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.6.3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          owner: coolsnowwolf
          base: master
          head: master
