name: Build Cudy TR3000 Firmware

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
        gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev \
        file wget llvm python3-pyelftools libpython3-dev aria2 jq qemu-utils ccache rename \
        libelf-dev device-tree-compiler libgmp3-dev libmpc-dev libfuse-dev

    - name: Clone OpenWrt source
      run: |
        git clone https://github.com/coolsnowwolf/lede openwrt
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configure for Cudy TR3000
      run: |
        cd openwrt
        # 设置目标设备为 Cudy TR3000（假设目标为 ramips/mt7621）
        echo "CONFIG_TARGET_ramips=y" >> .config
        echo "CONFIG_TARGET_ramips_mt7621=y" >> .config
        echo "CONFIG_TARGET_ramips_mt7621_DEVICE_cudy_tr3000=y" >> .config
        make defconfig

    - name: Compile OpenWrt
      run: |
        cd openwrt
        make -j$(($(nproc) + 1)) V=s

    - name: Upload firmware as artifact
      uses: actions/upload-artifact@v3
      with:
        name: cudy-tr3000-firmware
        path: openwrt/bin/targets/ramips/mt7621/*
