name: Build Cudy TR3000 Firmware (MT7981B)

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev libncursesw5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc wget unzip python3 python3-distutils

    - name: Clone OpenWrt source
      run: |
        git clone https://github.com/coolsnowwolf/lede.git openwrt
        cd openwrt
        git checkout v23.05.5

    - name: Update feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configure OpenWrt for MT7981B
      run: |
        cd openwrt
        echo "CONFIG_TARGET_mediatek=y" > .config
        echo "CONFIG_TARGET_mediatek_filogic=y" >> .config
        echo "CONFIG_TARGET_mediatek_filogic_DEVICE_cudy-tr3000=y" >> .config
        echo "CONFIG_PACKAGE_kmod-usb-net-rndis=y" >> .config
        echo "CONFIG_PACKAGE_luci-app-adguardhome=y" >> .config
        echo "CONFIG_PACKAGE_luci-app-turboacc=y" >> .config
        echo "CONFIG_PACKAGE_luci-app-ttyd=y" >> .config
        echo "CONFIG_PACKAGE_luci-app-sqm=y" >> .config
        echo "CONFIG_PACKAGE_luci-app-passwall2=y" >> .config
        echo "CONFIG_PACKAGE_nginx=y" >> .config
        echo "CONFIG_PACKAGE_luci-ssl=y" >> .config
        echo "CONFIG_PACKAGE_luci-app-uhttpd=y" >> .config
        echo "CONFIG_PACKAGE_luci-i18n-base-zh-cn=y" >> .config
        echo "CONFIG_PACKAGE_luci-i18n-adguardhome-zh-cn=y" >> .config
        echo "CONFIG_PACKAGE_luci-i18n-turboacc-zh-cn=y" >> .config
        echo "CONFIG_PACKAGE_luci-i18n-ttyd-zh-cn=y" >> .config
        echo "CONFIG_PACKAGE_luci-i18n-sqm-zh-cn=y" >> .config
        echo "CONFIG_PACKAGE_luci-i18n-passwall2-zh-cn=y" >> .config
        make defconfig

    - name: Build firmware
      run: |
        cd openwrt
        make -j$(nproc)

    - name: Upload firmware
      uses: actions/upload-artifact@v3
      with:
        name: cudy-tr3000-firmware
        path: openwrt/bin/targets/mediatek/filogic/*.bin

    - name: Customize firmware settings
      run: |
        cd openwrt
        echo "uci set network.lan.ipaddr='10.18.18.3'" >> custom.sh
        echo "uci set system.@system[0].hostname='CudyTR3000'" >> custom.sh
        echo "uci set system.@system[0].timezone='CST-8'" >> custom.sh
        echo "uci set system.@system[0].zonename='Asia/Shanghai'" >> custom.sh
        echo "uci set luci.main.lang='zh_cn'" >> custom.sh
        echo "uci set luci.main.mediaurlbase='/luci-static/bootstrap'" >> custom.sh
        echo "uci set luci.main.loginpath='TR3000/'" >> custom.sh
        echo "uci set luci.main.password='qwertyui'" >> custom.sh
        echo "uci commit" >> custom.sh
        chmod +x custom.sh
        ./custom.sh

    - name: Rebuild firmware with custom settings
      run: |
        cd openwrt
        make -j$(nproc)

    - name: Upload customized firmware
      uses: actions/upload-artifact@v3
      with:
        name: cudy-tr3000-custom-firmware
        path: openwrt/bin/targets/mediatek/filogic/*.bin
