#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: 网件wndr3800

on:
  push:
    branches: 
      - master
  # schedule:
  #   - cron: 0 20 * * *
  # release:
  #   types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: 校验本地文件
        uses: actions/checkout@master
        with:
          ref: master

      - name: 安装编译环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
      - name: 清理系统环境 
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          echo "Deleting files, please wait ..."
          sudo rm -rf \
            /usr/share/dotnet \
            /etc/mysql \
            /etc/php
          sudo -E apt-get -y purge \
            azure-cli \
            ghc* \
            zulu* \
            hhvm \
            llvm* \
            firefox \
            google* \
            dotnet* \
            powershell \
            openjdk* \
            mysql* \
            php*
      - name: 更新软件列表
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get update
      - name: 安装编译所需环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
      - name: 进行安装后的清理
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
      # - name: 构建自定义文件结构
      #  run: |
      #    cd package
      #    mkdir openwrt-packages
      #    cd openwrt-packages
      #    git clone https://github.com/openwrt-develop/luci-theme-atmaterial.git
      #    git clone https://github.com/KFERMercer/luci-app-serverchan
      #    git clone https://github.com/rosywrt/luci-theme-rosy
      #    git clone https://github.com/Ameykyl/luci-app-koolproxyR
          
      - name: 构建编译扩展环境
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: 导入自定义配置
        run: |
          rm -f ./.config*
          touch ./.config
          #
          # ========================固件定制部分========================
          # 
          # 
          # 如果不对本区块做出任何编辑, 则生成默认配置固件. 
          # 
          # 以下为定制化固件选项和说明:
          #
          #
          # 有些插件/选项是默认开启的, 如果想要关闭, 请参照以下示例进行编写:
          # 
          #          =========================================
          #         |  # 取消编译VMware镜像:                   |
          #         |  cat >> .config <<EOF                   |
          #         |  # CONFIG_VMDK_IMAGES is not set        |
          #         |  EOF                                    |
          #          =========================================
          #
          # 
          # 以下是一些提前准备好的一些插件选项.
          # 直接取消注释相应代码块即可应用. 不要取消注释代码块上的汉字说明.
          # 如果不需要代码块里的某一项配置, 只需要删除相应行.
          #
          # 如果需要其他插件, 请按照示例自行添加.
          # 注意, 只需添加依赖链顶端的包. 如果你需要插件 A, 同时 A 依赖 B, 即只需要添加 A.
          # 
          # 无论你想要对固件进行怎样的定制, 都需要且只需要修改 EOF 回环内的内容.
          # 
          # 编译wndr3800固件:
           cat >> .config <<EOF
           CONFIG_TARGET_ar71xx=y
           CONFIG_TARGET_ar71xx_generic=y
           CONFIG_TARGET_ar71xx_generic_DEVICE_wndr3800=y
           EOF
          # 设置固件大小:
          # cat >> .config <<EOF
          # CONFIG_TARGET_KERNEL_PARTSIZE=30
          # CONFIG_TARGET_ROOTFS_PARTSIZE=400
          # EOF 
          # 固件压缩:
           cat >> .config <<EOF
           CONFIG_TARGET_IMAGES_GZIP=y
           EOF
          # 编译UEFI固件:
          # cat >> .config <<EOF
          # CONFIG_EFI_IMAGES is not set
          # EOF
          # IPv6支持:
           cat >> .config <<EOF
           CONFIG_PACKAGE_dnsmasq_full_dhcpv6=y
           CONFIG_PACKAGE_ipv6helper=y
           EOF
          # 多文件系统支持:
          # cat >> .config <<EOF
          # CONFIG_PACKAGE_kmod-fs-nfs is not set
          # CONFIG_PACKAGE_kmod-fs-nfs-common is not set
          # CONFIG_PACKAGE_kmod-fs-nfs-v3 is not set
          # CONFIG_PACKAGE_kmod-fs-nfs-v4 is not set
          # CONFIG_PACKAGE_kmod-fs-ntfs is not set
          # CONFIG_PACKAGE_kmod-fs-squashfs is not set
          # EOF
          # USB3.0支持:
          # cat >> .config <<EOF
          # CONFIG_PACKAGE_kmod-usb-ohci is not set
          # CONFIG_PACKAGE_kmod-usb-ohci-pci is not set
          # CONFIG_PACKAGE_kmod-usb2 is not set
          # CONFIG_PACKAGE_kmod-usb2-pci is not set
          # CONFIG_PACKAGE_kmod-usb3 is not set
          # EOF
          # 常用LuCI插件选择:
           cat >> .config <<EOF
           CONFIG_PACKAGE_6in4=y
           CONFIG_PACKAGE_adbyby is not set
           CONFIG_PACKAGE_automount is not set
           CONFIG_PACKAGE_bash is not set
           CONFIG_PACKAGE_coreutils is not set
           CONFIG_PACKAGE_etherwake is not set
           CONFIG_PACKAGE_ip-full is not set
           CONFIG_PACKAGE_ip6tables=y
           CONFIG_PACKAGE_ipset is not set
           CONFIG_PACKAGE_iptables-mod-conntrack-extra is not set
           CONFIG_PACKAGE_iptables-mod-ipopt is not set
           CONFIG_PACKAGE_iptables-mod-ipsec is not set
           CONFIG_PACKAGE_iptables-mod-tproxy is not set
           CONFIG_PACKAGE_ipv6helper=y
           CONFIG_PACKAGE_kmod-crypto-cbc is not set
           CONFIG_PACKAGE_kmod-crypto-deflate is not set
           CONFIG_PACKAGE_kmod-crypto-des is not set
           CONFIG_PACKAGE_kmod-crypto-echainiv is not set
           CONFIG_PACKAGE_kmod-crypto-hmac is not set
           CONFIG_PACKAGE_kmod-crypto-md5 is not set
           CONFIG_PACKAGE_kmod-crypto-rng is not set
           CONFIG_PACKAGE_kmod-crypto-sha256 is not set
           CONFIG_PACKAGE_kmod-crypto-wq is not set
           CONFIG_PACKAGE_kmod-fs-exfat is not set
           CONFIG_PACKAGE_kmod-fs-ext4 is not set
           CONFIG_PACKAGE_kmod-fs-vfat is not set
           CONFIG_PACKAGE_kmod-fuse is not set
           CONFIG_PACKAGE_kmod-gre is not set
           CONFIG_PACKAGE_kmod-ifb is not set
           CONFIG_PACKAGE_kmod-ipsec is not set
           CONFIG_PACKAGE_kmod-ipt-conntrack-extra is not set
           CONFIG_PACKAGE_kmod-ipt-ipopt is not set
           CONFIG_PACKAGE_kmod-ipt-ipsec is not set
           CONFIG_PACKAGE_kmod-ipt-nat6=y
           CONFIG_PACKAGE_kmod-ipt-tproxy is not set
           CONFIG_PACKAGE_kmod-iptunnel6 is not set
           CONFIG_PACKAGE_kmod-lib-crc16 is not set
           CONFIG_PACKAGE_kmod-nf-conntrack-netlink is not set
           CONFIG_PACKAGE_kmod-nf-nat6=y
           CONFIG_PACKAGE_kmod-nls-base is not set
           CONFIG_PACKAGE_kmod-nls-cp437 is not set
           CONFIG_PACKAGE_kmod-nls-iso8859-1 is not set
           CONFIG_PACKAGE_kmod-nls-utf8 is not set
           CONFIG_PACKAGE_kmod-sched-cake is not set
           CONFIG_PACKAGE_kmod-scsi-core is not set
           CONFIG_PACKAGE_kmod-sit=y
           CONFIG_PACKAGE_kmod-tun is not set
           CONFIG_PACKAGE_kmod-usb-core is not set
           CONFIG_PACKAGE_kmod-usb-storage is not set
           CONFIG_PACKAGE_kmod-usb-storage-extras is not set
           CONFIG_PACKAGE_libelf is not set
           CONFIG_PACKAGE_libgmp is not set
           CONFIG_PACKAGE_libipset is not set
           CONFIG_PACKAGE_libminiupnpc is not set
           CONFIG_PACKAGE_libmnl is not set
           CONFIG_PACKAGE_libnatpmp is not set
           CONFIG_PACKAGE_libncurses is not set
           CONFIG_PACKAGE_libreadline is not set
           CONFIG_PACKAGE_libstdcpp is not set
           CONFIG_PACKAGE_luci-app-accesscontrol is not set
           CONFIG_PACKAGE_luci-app-adbyby-plus is not set
           CONFIG_PACKAGE_luci-app-arpbind is not set
           CONFIG_PACKAGE_luci-app-ddns is not set
           CONFIG_PACKAGE_luci-app-filetransfer is not set
           CONFIG_PACKAGE_luci-app-ipsec-vpnd is not set
           CONFIG_PACKAGE_luci-app-nlbwmon is not set
           CONFIG_PACKAGE_luci-app-pptp-server is not set
           CONFIG_PACKAGE_luci-app-sqm is not set
           CONFIG_PACKAGE_luci-app-ssr-plus is not set
           CONFIG_PACKAGE_luci-app-vsftpd is not set
           CONFIG_PACKAGE_luci-app-wol is not set
           CONFIG_PACKAGE_luci-app-xlnetacc is not set
           CONFIG_PACKAGE_luci-app-zerotier is not set
           CONFIG_PACKAGE_luci-lib-fs is not set
           CONFIG_PACKAGE_luci-proto-ipv6=y
           CONFIG_PACKAGE_nlbwmon is not set
           CONFIG_PACKAGE_ntfs-3g is not set
           CONFIG_PACKAGE_odhcp6c=y
           CONFIG_PACKAGE_odhcp6c_ext_cer_id=0
           CONFIG_PACKAGE_odhcpd-ipv6only=y
           CONFIG_PACKAGE_odhcpd_ipv6only_ext_cer_id=0
           CONFIG_PACKAGE_pptpd is not set
           CONFIG_PACKAGE_shadowsocksr-libev-alt is not set
           CONFIG_PACKAGE_sqm-scripts is not set
           CONFIG_PACKAGE_strongswan is not set
           CONFIG_PACKAGE_strongswan-charon is not set
           CONFIG_PACKAGE_strongswan-ipsec is not set
           CONFIG_PACKAGE_strongswan-minimal is not set
           CONFIG_PACKAGE_strongswan-mod-aes is not set
           CONFIG_PACKAGE_strongswan-mod-gmp is not set
           CONFIG_PACKAGE_strongswan-mod-hmac is not set
           CONFIG_PACKAGE_strongswan-mod-kernel-netlink is not set
           CONFIG_PACKAGE_strongswan-mod-nonce is not set
           CONFIG_PACKAGE_strongswan-mod-pubkey is not set
           CONFIG_PACKAGE_strongswan-mod-random is not set
           CONFIG_PACKAGE_strongswan-mod-sha1 is not set
           CONFIG_PACKAGE_strongswan-mod-socket-default is not set
           CONFIG_PACKAGE_strongswan-mod-stroke is not set
           CONFIG_PACKAGE_strongswan-mod-updown is not set
           CONFIG_PACKAGE_strongswan-mod-x509 is not set
           CONFIG_PACKAGE_strongswan-mod-xauth-generic is not set
           CONFIG_PACKAGE_strongswan-mod-xcbc is not set
           CONFIG_PACKAGE_tc is not set
           CONFIG_PACKAGE_terminfo is not set
           CONFIG_PACKAGE_vsftpd-alt is not set
           CONFIG_PACKAGE_zerotier is not set
           CONFIG_TARGET_ar71xx_nand_DEVICE_NBG6716 is not set
           CONFIG_TARGET_ar71xx_nand_DEVICE_R6100 is not set
           CONFIG_TARGET_ar71xx_nand_DEVICE_WNDR3700V4 is not set
           CONFIG_TARGET_ar71xx_nand_DEVICE_WNDR4300V1 is not set
           CONFIG_TARGET_ar71xx_nand_DEVICE_c-60 is not set
           CONFIG_TARGET_ar71xx_nand_DEVICE_domywifi-dw33d is not set
           CONFIG_TARGET_ar71xx_nand_DEVICE_hiveap-121 is not set
           CONFIG_TARGET_ar71xx_nand_DEVICE_mr18 is not set
           CONFIG_TARGET_ar71xx_nand_DEVICE_rambutan is not set
           CONFIG_TARGET_ar71xx_nand_DEVICE_sbr-ac1750 is not set
           CONFIG_TARGET_ar71xx_nand_DEVICE_wi2a-ac200i is not set
           CONFIG_TARGET_ar71xx_nand_DEVICE_z1 is not set
           CONFIG_TARGET_ar71xx_nand_Default is not set
           CONFIG_TARGET_ath25_DEVICE_generic is not set
           CONFIG_TARGET_ath25_DEVICE_ubnt2 is not set
           CONFIG_TARGET_ath25_DEVICE_ubnt2-pico2 is not set
           CONFIG_TARGET_ath25_DEVICE_ubnt5 is not set
           CONFIG_TARGET_ath25_Default is not set
           EOF
          # LuCI主题:
           cat >> .config <<EOF
           CONFIG_PACKAGE_luci-theme-bootstrap=y
           EOF
          # 常用软件包:
          # cat >> .config <<EOF
          # CONFIG_PACKAGE_curl=y
          # CONFIG_PACKAGE_htop=y
          # CONFIG_PACKAGE_nano=y
          # CONFIG_PACKAGE_screen=y
          # CONFIG_PACKAGE_tree=y
          # CONFIG_PACKAGE_vim-fuller=y
          # CONFIG_PACKAGE_wget=y
          # EOF
          # 取消编译VMware镜像以及镜像填充 (不要删除被缩进的注释符号):
          # cat >> .config <<EOF
          # # CONFIG_TARGET_IMAGES_PAD is not set
          # # CONFIG_VMDK_IMAGES is not set
          # EOF
          # 其他需要安装的软件包:
          # cat >> .config <<EOF
          # CONFIG_PACKAGE_iptables-mod-nat-extra=y
          # CONFIG_PACKAGE_luci-i18n-uhttpd-zh-cn=y
          # CONFIG_PACKAGE_luci-ssl-openssl=y
          # EOF
          # 
          # ========================固件定制部分结束========================
          # 
          sed -i 's/^[ \t]*//g' ./.config
          make defconfig
      - name: 下载编译所需源码
        run: |
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;
      - name: 进行固件编译
        run: |
          echo -e "$(nproc) thread build."
          make -j$(nproc) V=s
          
      - name: 清理不必要的文件
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          find ./bin/targets/ -name "*combined*img*" | xargs -i mv -f {} ./artifact/
          find ./bin/targets/ -name "*sysupgrade*bin*" | xargs -i mv -f {} ./artifact/
      - name : 上传固件
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt firmware
          path: bin/targets
